### ISSUE TITLE
insurgancy sandstorm unable to create instance 

### ISSUE THREAD

**Issue by Lead-Problem** [CubeCoders/AMPTemplates#1019]
i am unable to create an insurgancy sand storm instance 
in the deployment log i get this error

Non-managed instances exist, autoconfigure cannot guarantee that the configuration is valid!
Failed to unpack AMP.
KeyNotFoundException
[0] (KeyNotFoundException) : The given key 'GenericModule.Meta.MinAMPVersion' was not present in the dictionary.
  at Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) 
  at InstanceManagerPlugin.LocalInstanceManager.DownloadAndUnpack (InstanceManagerPlugin.LocalAMPInstance Spec, Boolean SkipCache) 

Create Instance Failed: The core archive failed to download or unpack: Failed to unpack AMP: The given key 'GenericModule.Meta.MinAMPVersion' was not present in the dictionary.

i have restarted the server and fetched latest in instance deployment still getting the same issue 
Currently running version 2.5.1.8 - 20240917.2

**Comment by IceOfWraith** [comment]
Assuming you're on Windows, you need to install git:

https://discourse.cubecoders.com/t/amp-dependencies-git/1803

Then go into File Manager and navigate to `ADS01/Plugins/ADSModule/DeploymentTemplates` and delete all folders inside.

Last search for `repo` in the top right and click the Fetch button.

**Comment by IceOfWraith** [comment]
Hold that thought actually... looks like that template is missing it.

**Comment by IceOfWraith** [comment]
This is solved. Fetch the repo again and make a new instance.
