### ISSUE TITLE
Discord.JS Hosting

### ISSUE THREAD

**Issue by augesrob** [CubeCoders/AMPTemplates#103]
# Module Request

Discord.JS

## Game Information:

Game Title: Discord.js
How to obtain: 
Need to be able to install node.js https://nodejs.org/en/
To start the script need away to start with custom .js file example index.js

Suppoted OSs: Any

Supports RCON/Console input?
Need to be able to run 'npm install <object>' in console

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [ ] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by jasperfirecai2** [comment]
there is a docker image for amp that comes with node pre-installed. this isn't really a game nor a particular application. I don't think this really can fall under a configurable generic module, rather should just be hosted with a manually configured node.js image. Thinks like which file to run, what commands exist in console, which ports to open etc will depend entirely on which bot you're hosting

**Comment by PhonicUK** [comment]
Redundant - you can already do this. I might ship an example though because this really is simple to do.

**Comment by MrMcyeet** [comment]
> Redundant - you can already do this. I might ship an example though because this really is simple to do.

That would be both awesome and quite helpful.

**Comment by IceOfWraith** [comment]
What's a commonly used bot that uses node.js? I can get a template created to use as an example. The GatekeeperV2 template works similarly as it uses a Python bot and the Python Docker image. So it would just be an adjustment to node.js instead.
