### ISSUE TITLE
Minecraft Bungeecord Waterfall

### ISSUE THREAD

**Issue by Pingger** [CubeCoders/AMPTemplates#105]
# Module Request

Request for the Bungeecord config to also allow using 'Waterfall' to be used (which is a fork of bungeecord by papermc, with several QOL and performance improvements).

## Game Information:

Game Title: Minecraft Waterfall Proxy
How to obtain: https://papermc.io/downloads#Waterfall
Suppoted OSs: Java 17 compatible
Supports RCON/Console input? yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- ~~that the server is an official server distributed by the games publishers/developers.~~ Not applicable
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by IceOfWraith** [comment]
This should be requested in the AMP repo as it's part of the proprietary Minecraft module. Only Mike has access to change that code. Sorry for not catching this sooner.
