### ISSUE TITLE
Additional Ark Survival Ascended UI Settings

### ISSUE THREAD

**Issue by Gomezb3** [CubeCoders/AMPTemplates#1099]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Ark Survival Ascended
How to obtain: [Steam Link](https://store.steampowered.com/app/2399830/ARK_Survival_Ascended/)
Suppoted OSs: Windows, Linux?
Supports RCON/Console input? Yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

A setting that is missing in the UI that can be applied through command line flags is dino event colors. I believe this would be greatly beneficial to all those hosting ASA servers as these command line flags **NEED** to be set for dinos to have the event colors, even if the event mod is enabled. [Ark wiki](https://ark.wiki.gg/wiki/Server_configuration) has some of the colors listed, but not all. To my knowledge, there is -EasterColors, -PrideColors, -OlympicColors, and as of yesterday, -HalloweenColors.

I went ahead and edited the GenericModule.kvp and added the following in configmanifest.json in a testing instance to test this and it seems to work:

>     {
>         "DisplayName":"Dino Colors",
>         "Category":"ARK SA:stadia_controller",
>         "Subcategory":"Server:dns:1",
>         "Description":"Sets dino colors",
>         "Keywords":"colors,event",
>         "FieldName":"Colors",
>         "InputType":"enum",
>         "ParamFieldName":"Colors",
>         "DefaultValue":"",
>         "EnumValues":{
>             "":"None",
>             "-EasterColors":"Easter Colors",
>             "-HalloweenColors":"Halloween Colors",
>             "-OlympicColors":"Olympic Colors",
>             "-PrideColors":"Pride Colors"
>         }
>     },

**Comment by Greelan** [comment]
Thanks. Feel free to create a PR for the two ASA templates

**Comment by Gomezb3** [comment]
> Thanks. Feel free to create a PR for the two ASA templates

Done, ty.
