### ISSUE TITLE
OpenTTD

### ISSUE THREAD

**Issue by Foxior** [CubeCoders/AMPTemplates#11]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title:
How to obtain: https://openttd.org, Steam
Suppoted OSs: Windows, Linux, OS X, FreeBSD
Supports RCON/Console input? Yes

## I confirm:

- [X] that I have searched for an existing module request for this application.
- [X] that the server is an official server distributed by the games publishers/developers.
- [X] that the server is available to the general public.
- [X] that the server can be run headless (without a GUI).
- [X] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

My config: [openttd.zip](https://github.com/CubeCoders/AMPTemplates/files/7719293/openttd.zip)
It installs using SteamCMD and tries to start, but only with a message that it can not run.

**Comment by xLeviNx** [comment]
[openttd.zip](https://github.com/CubeCoders/AMPTemplates/files/7728836/openttd.zip)

Try this

**Comment by Foxior** [comment]
This is weird... I've deleted my instance of OTTD and installed yours. It finished correctly but went into loop for asking my steam credentials (2FA). Then I deleted it and loaded my version, and now it works. It loaded my saved game. I Will Try to copy my config file to it and to connect.
Earlier when I wanted it to start, it just displayed basic information about game components available (SFX, MSX, GFX modes etc.). On the top of the console frame it displayed a message that it can not be run and that's the only error message I got.

**Comment by xLeviNx** [comment]
Not sure then, although the login can be fixed by using the steam auth as anonymous. All I did was verify the game file to have the dedicated server parameter and worked for me. 

Also the ports listed on mine are the correct ones based on the wiki on their website
