### ISSUE TITLE
Super Monday Night Combat

### ISSUE THREAD

**Issue by Buwop** [CubeCoders/AMPTemplates#1112]
Game Title:
Super Monday Night Combat

How to obtain:
You can obtain Super Monday Night Combat through Steam (though it's discontinued, it might still be available via other channels). You can include the Steam page URL, or mention the game’s status if it's no longer being officially sold:

    Steam Page: https://store.steampowered.com/app/94600/Super_Monday_Night_Combat/

Supported OSs:
Windows (and possibly Linux, depending on community or user reports regarding compatibility)

Supports RCON/Console input?
If the game has a server-side console (which many games do for administration), you can confirm whether it has RCON or other console support. This is likely a community feature if Super Monday Night Combat servers support remote console access. Based on the game’s legacy, it’s worth checking through official docs or community resources for whether it offers RCON support or can be configured through the server files.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [ ] that the server is an official server distributed by the games publishers/developers.
- [ ] that the server is available to the general public.
- [ ] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by IceOfWraith** [comment]
The devs never released a dedicated server for this game. It seems like Monday Night Combat might be an option, but not Super Monday Night Combat.

If you can find that a dedicated server was created somewhere, please feel free to share and we can look into it.
