### ISSUE TITLE
Request to specify a log path for 7D2D

### ISSUE THREAD

**Issue by NZScruffy** [CubeCoders/AMPTemplates#1113]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: 7 Days to Die
How to obtain: [https://](https://store.steampowered.com/app/251570/7_Days_to_Die/)
Suppoted OSs: Windows, Linux
Supports RCON/Console input? Yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

# Request to specify Log Path:
Please add a default log path to command-line, or ability to specify a log path in settings. The command-line argument would look like this:

`-logfile 7DaysToDieServer_Data\output_log%LOGTIMESTAMP%.txt`

The default dedicated server script has the location for the logs in `7DaysToDieServer_Data` folder. 

## Reason for request:
Currently the instance stores the logs in `<instance>/AMP_Logs`. In order to give users access to the logs, they would have to be given access to ADS, which is a security issue. This request would allow moving the log location to a folder with user instance access.

**Comment by IceOfWraith** [comment]
You're looking at the AMP logs there. The server has its own sets of logs the will look similar. Here's a reference that might help. Haven't verified myself.

https://steamcommunity.com/app/251570/discussions/1/1734336452587854805/

**Comment by Greelan** [comment]
The log is indeed in the 7DaysToDieServer_Data directory in the instance datastore

**Comment by NZScruffy** [comment]
> The log is indeed in the 7DaysToDieServer_Data directory in the instance datastore

In the 3 instances we have running, none of them have any logs in the `7DaysToDieServer_Data` folder. I have noticed other users on Discord commenting the same. The logs are not there.

**Comment by Greelan** [comment]
What OS?

**Comment by NZScruffy** [comment]
> What OS?

OS | Linux
-- | --
Platform | Debian GNU/Linux 12

**Comment by Greelan** [comment]
Interesting. I have two running on ARM in docker. The 1.1 server has the log. The A21.2 server doesn't. 

It's not an issue as such to add the flag, provided it doesn't then mess with the console output.

**Comment by NZScruffy** [comment]
That would be much appreciated. Thanks.

**Comment by Greelan** [comment]
Yeah, adding the -logfile line means that most of the console output disappears, which is not ideal

**Comment by Greelan** [comment]
Why don't you add a virtual dir in the instance that points to the instance's AMP_Logs dir and therefore makes it accessible in the instance file manager?
