### ISSUE TITLE
VRising Configuration not working

### ISSUE THREAD

**Issue by Raven44380** [CubeCoders/AMPTemplates#1118]
After speaking with PotatoKing it was recommended to come here to report an issue.

To start, the AMP instances are all upgraded to the latest versions and the latest template has been grabbed before hand.
Any changes inputted within the configuration fields for the VRising instance do not get reflected within the game nor change and while looking into it further the configuration changes are being added to the following path:

/save-data/setttings/ServerGameSettings.json

If I go to path below and manually input the settings that I would like to have changed, they will reflect in the game and work properly but as of right now the only fields that work properly are the ones within the "Host" tab.

VRisingServer_Data/StreamingAssets/GameSettingPresets/StandardPvE.json

The path above is the one I am trying to use and have changes wrote too but as I mentioned, if I make changes in here manually they work just fine.

**Comment by Greelan** [comment]
Trying to understand this. Are you saying `save-data/setttings/ServerGameSettings.json` doesn't get used at all, even if manual changes are made?

Or are you saying that changes in the UI are not reflected in that file?

**Comment by Greelan** [comment]
Also, what are your "Game Settings Ruleset" and "Game Difficulty Preset" set to under the Host tab?

**Comment by Raven44380** [comment]
You'd be correct, the save-data/setttings/ServerGameSettings.json doesn't get used at all. Under the host setting tab, if I lets say select StandardPvE for the rules and if I then navigate to VRisingServer_Data/StreamingAssets/GameSettingPresets/StandardPvE.json and make the changed I want there they will actually work.

Any changes made to save-data/setttings/ServerGameSettings.json from the GUI will show that they were made to that file in that path but wont work at all.

**Comment by Greelan** [comment]
That's the point of a preset though, it overrides custom settings

**Comment by Raven44380** [comment]
I see, so what you're saying is if I am to select the GamePresent StandardPvE any changes I make in the GUI won't be added to that present then and if I want to make any changes using the GUI I literally have to use the Custom one?

**Comment by Raven44380** [comment]
If that is the case, can we add the ability to be able change these presets from the GUI and not have to go in manually?

**Comment by Greelan** [comment]
Why bother with the preset at all then?
