### ISSUE TITLE
Adding Hurtworld server to amp.

### ISSUE THREAD

**Issue by Terskipia** [CubeCoders/AMPTemplates#113]
Please add a option to install hurtworld Servers to amp. Thanks.

**Comment by Greelan** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/114/files

**Comment by Greelan** [comment]
@Terskipia, have you got a Hurtworld server running already (outside AMP)? If so, do you have world saves and loads working, and how? Following the (minimal) guides on the web doesn't seem to create a save file, using the `saveserver` option on the command line.

**Comment by PhonicUK** [comment]
Hurtworld was added in a recent update. Although this issue should have been deleted anyway for not following the template.
