### ISSUE TITLE
Soulmask - Appmanifest not found

### ISSUE THREAD

**Issue by Shadowsong87** [CubeCoders/AMPTemplates#1148]
Since updates were released in the latest round of updates, i've been testing some games. Soulmask's updates are broken, it is unable to find the app manifest file.

[20:40:59] [steamcmdplugin Info/5] : Checking current version info for 3017310...
[20:40:59] [steamcmdplugin Error/5] : App manifest file not found: ./soulmask/3017310\steamapps\appmanifest_3017310.acf
[20:40:59] [steamcmdplugin Error/5] : Current build ID is 0. Cannot check for updates.

If I open file explorer on the instance, go into the steamapps folder the manifest is present. 

OS: Server 2022

Let me know if you need anymore info.

**Comment by Greelan** [comment]
Delete the steamapps dir, try updating again

Also basic info like OS would be helpful

**Comment by Greelan** [comment]
@IceOfWraith the scheduler logic is making an assumption about the install_dir rather than referring to the template. Soulmask has separate steam app IDs for the windows and Linux servers and therefore the template uses `server` as the base dir/install_dir

**Comment by IceOfWraith** [comment]
Nice. The new update stages logging is doing as expected. I'll get the code adjusted.

Thanks!

**Comment by IceOfWraith** [comment]
It looks like it's based on the RootDir. Is there anything stopping the template from being adjusted to point to `./soulmask/server/` for the Root?

**Comment by Greelan** [comment]
Other than that it would likely mess with existing instances. Can't it just look at UpdateSourceTarget if set?

**Comment by Greelan** [comment]
I don't think it's a good idea to create an anomaly for this sort of situation given it is not the only example of a server having platform specific app IDs

**Comment by IceOfWraith** [comment]
I can see about adjusting it to look for a target. It just didn't look like the template used the RootDir for anything and since it's relative it seemed like an easy adjustment to solve for it.

**Comment by Greelan** [comment]
Well, SteamCMD is installed in the root dir as per normal. Probably better not to mix the SteamCMD installation and the server installation

**Comment by IceOfWraith** [comment]
This is addressed in the next release.
