### ISSUE TITLE
SCP Labrat

### ISSUE THREAD

**Issue by cadergator10** [CubeCoders/AMPTemplates#1151]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title:
How to obtain: https://store.steampowered.com/app/1402020/SCP_Labrat/ : Client
https://steamdb.info/app/2261800/depots/ : Server
Suppoted OSs: Server: Linux & Windows
Supports RCON/Console input? I believe RCON but not exactly sure.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

**Comment by p0t4t0sandwich** [comment]
Is that the same game as this template here?
https://github.com/CubeCoders/AMPTemplates/blob/main/scp-secret-laboratory.kvp

**Comment by cadergator10** [comment]
> Is that the same game as this template here? https://github.com/CubeCoders/AMPTemplates/blob/main/scp-secret-laboratory.kvp

No, this is SCP Labrat. It's a VR version of SCP Containment Breach that does have a multiplayer mode

**Comment by p0t4t0sandwich** [comment]
Ah okay, I was just checking since the issue's title matched the existing template

**Comment by cadergator10** [comment]
> Ah okay, I was just checking since the issue's title matched the existing template

Oh yeah my bad XD. I had secret lab on the mind writing this since the new beta came out lol

**Comment by cadergator10** [comment]
> Template in `Greelan/AMPTemplates:dev`
> 
> Bit bizarre that with this one you launch an RCON exe which then launches the server. Means on windows that the metrics monitoring is off (AMP monitors the RCON exe)

Thank you!

**Comment by Greelan** [comment]
Let me know any comments/issues, so that I can merge it to the main repo
