### ISSUE TITLE
Valhiem Plus - Max Supported Players

### ISSUE THREAD

**Issue by SardinasA** [CubeCoders/AMPTemplates#116]
Can support for changing MAX Player be added to Valhiem Plus?

I would suspect for the valheimconfig.json file it would be to add the following

  {
    "DisplayName": "Max Players",
    "Description": "Max Players to connect to Server",
    "FieldName": "maxPlayers",
    "InputType": "text",
    "Category": "Server",
    "ParamFieldName": "maxPlayers",
    "IncludeInCommandLine": true,
    "DefaultValue": "10"
  },

**Comment by IceOfWraith** [comment]
This definitely looks doable now with the improvements to AMP over the last few months. It seems there are hundreds of settings, so if you choose the most desired they could be implemented pretty easily.

**Comment by gOOvER** [comment]
I would suggest removing v+ and just installing BepInex.  so everyone can decide for themselves what mods they want to use

**Comment by gkuba** [comment]
I'll be looking into this shortly.

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/241
