### ISSUE TITLE
tarkov-fika - Startup issue due to system locale

### ISSUE THREAD

**Issue by IAMBUDE** [CubeCoders/AMPTemplates#1162]
Hi, I'm new here so pardon me if this issue is created incorrectly.

There's a rather small problem with the tarkov-fika AMP configuration.
If the host OS is using a non-english locale, SPT will use the translation files for the console output:
![image](https://github.com/user-attachments/assets/0ea51f68-0699-4255-ab0e-b41c191deff4)
This causes AMP to not complete the startup step, since it can't find the phrase `Server is running, do not close while playing SPT.`

The fix for this is rather simple, AMP just needs to change the SPT_Data\Server\configs\locale.json file and change the following variables
`"gameLocale": "system",`
`"serverLocale": "system",`
to
`"gameLocale": "en",`
`"serverLocale": "en",`

With this, the locale support goes out the window and everything will be displayed in english but this allows AMP to recognize the startup phrase again:
![image](https://github.com/user-attachments/assets/418b24db-12b9-4af8-80d2-217b53439871)

As an alternative to changing the language, you could maybe look for the websocket and server port messages, using the IP + port combination as a startup phrase, since those should be the last step before the server gets the ready message.

**Comment by Greelan** [comment]
The regex could also just be updated to have language alternatives that users request

**Comment by Greelan** [comment]
Post the actual German text here (rather than a screenshot) and I can add it

**Comment by Greelan** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/1164

**Comment by IAMBUDE** [comment]
@Greelan sorry I couldn't get back to you in a timely manner. Thank you very much for fixing this issue. 

I don't know if you or anyone else for that matter would also want to deal with all the current available translations, but if so, here are the variables for the server_running text.

**en.json - reference**
`"server_running": "Server is running, do not close while playing SPT",`

**ar.json**
`"server_running": "الخادم قيد التشغيل، لا تغلقه أثناء تشغيل SPT",`

**cs.json**
`"server_running": "Server je spušťen, nezavírat při hraní SPT",`

**de.json**
`"server_running": "Der Server läuft. Schließen Sie ihn nicht, während Sie SPT spielen",`

**el.json**
`"server_running": "Ο διακομιστής εκτελείται, μην κλείσετε κατά την αναπαραγωγή του SPT",`

**es-es.json**
`"server_running": "El servidor está funcionando.",`

**fr.json**
`"server_running": "Le serveur est en cours d'exécution, ne le fermez pas pendant que vous jouez à SPT",`

**hu.json**
`"server_running": "A szerver fut, ne zárd be, amíg az SPT-vel játszol",`

**id.json**
`"server_running": "Server sedang berjalan, jangan dimatikan saat main SPT",`

**it.json**
`"server_running": "Server è in esecuzione",`

**ja.json**
`"server_running": "サーバーが実行中。",`

**ko.json**
`"server_running": "서버가 실행 중입니다",`

**nl.json**
`"server_running": "Server is gestart",`

**no.json**
`"server_running": "Serveren kjører, ikke lukk mens du spiller SPT",`

**pl.json**
`"server_running": "Serwer jest uruchomiony. Nie wyłączaj podczas gry w SPT",`

**pt-br.json**
`"server_running": "O servidor está em execução, não feche enquanto estiver jogando SPT",`

**pt-pt.json**
`"server_running": "Servidor está a correr, não fechar enquanto estiveres a jogar SPT",`

**ru.json**
`"server_running": "Сервер запущен",`

**sv-se.json**
`"server_running": "Servern körs",`

**tr.json**
`"server_running": "Sunucu çalışıyor",`

**zh-cn.json**
`"server_running": "服务端正在运行",`

**zh-TW.json**
`"server_running": "伺服器正在運行，玩SPT時請勿關閉",`
