### ISSUE TITLE
Valheim Plus - Ability to Edit Valheim Plus Configs via AMP Console

### ISSUE THREAD

**Issue by SardinasA** [CubeCoders/AMPTemplates#117]
Thanks for the great work @PhonicUK 

Would it be possible to have AMP edit the configs of Valheim Plus?

**Comment by SardinasA** [comment]
https://github.com/rr222cy/ValheimPlus-Manager

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/241
