### ISSUE TITLE
Game request Teeworlds

### ISSUE THREAD

**Issue by TheBauer99** [CubeCoders/AMPTemplates#1178]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Teeworlds
How to obtain: https://www.teeworlds.com/?page=docs&wiki=server_setup
Suppoted OSs: Win & Linux
Supports RCON/Console input? ?/yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Template in `Greelan/AMPTemplates:dev`. Should be fully working but I will still do some clean-up of the settings

**Comment by TheBauer99** [comment]
Thank You very much, and Merry Xmas.
Works like a Charm.
