### ISSUE TITLE
AMP Configuration Generator Using Incorrect Steam AppID

### ISSUE THREAD

**Issue by IceOfWraith** [CubeCoders/AMPTemplates#13]
https://config.getamp.sh/ has a bug that the template generated uses the server AppID instead of the client ID. This causes Steam to not list the dedicated server on the server lists and attempts to launch the same dedicated server app when direct connecting, rather than the client app.

The issue was noted using the details below:

sven-co-op.kvp contains the following line which is what Steam uses to identify the app to open:

`App.EnvironmentVariables={"LD_LIBRARY_PATH": "./linux64:%LD_LIBRARY_PATH%", "SteamAppId": "276060"}`

AMP Configuration Generator Export:

`{"Meta_DisplayName":"Sven Co-op","Meta_Description":"","Meta_Author":"IceOfWraith","Meta_URL":"https://store.steampowered.com/app/225840/Sven_Coop/","_SupportsWindows":true,"_SupportsLinux":true,"App_AdminMethod":"SourceRCON","App_HasReadableConsole":true,"App_HasWritableConsole":true,"App_DisplayName":"Sven Co-op","App_CommandLineArgs":"-console +ip {{$ApplicationIPBinding}} -port {{$ApplicationPort1}} -sport {{$ApplicationPort2}} +rconpassword \"{{$RemoteAdminPassword}}\" +log on {{$FormattedArgs}}","App_CommandLineParameterFormat":"+{0} \"{1}\"","App_CommandLineParameterDelimiter":" ","App_RapidStartup":"true","App_ApplicationReadyMode":"Immediate","App_ExitMethod":"Kill","App_ExitString":"stop","Console_ThrowawayMessageRegex":"","Console_AppReadyRegex":"^Connection to Steam servers successful.$","Console_UserJoinRegex":"^User (?<username>.+?) \\((?<userid>-?d+)\\) connected from \\[::ffff:(?<endpoint>.+?)\\]$","Console_UserLeaveRegex":"^User (?<username>.+?) \\((?<userid>-?d+)\\) disconnected\\. Reason: (.+?)$","Console_UserChatRegex":"^(?<username>.+?): (?<message>.+)$","_PortMappings":[{"Port":"27015","PortType":"0"},{"Port":"26900","PortType":"0"}],"_UpdateSourceType":"4","_UpdateSourceURL":"","_UpdateSourceGitRepo":"","_UpdateSourceUnzip":false,"_DisplayImageSource":"","_SteamServerAppID":"276060","_SteamClientAppID":"225840","_WinExecutableName":"svends.exe","_LinuxExecutableName":"svends.exe","_AppSettings":[{"DisplayName":"Map","Category":"","Description":"Select the starting map.","Keywords":"map level","FieldName":"map","InputType":"text","IsFlagArgument":false,"ParamFieldName":"map","IncludeInCommandLine":true,"DefaultValue":"_server_start","_CheckedValue":"true","_UncheckedValue":"false","EnumValues":{}},{"DisplayName":"Max Players","Category":"","Description":"Max number of players (32 limit)","Keywords":"players users","FieldName":"maxplayers","InputType":"number","IsFlagArgument":false,"ParamFieldName":"maxplayers","IncludeInCommandLine":true,"DefaultValue":"10","_CheckedValue":"true","_UncheckedValue":"false","EnumValues":{}}],"Meta_OS":3,"Meta_ConfigManifest":"sven-co-opconfig.json","Meta_ConfigRoot":"sven-co-op.kvp","Meta_DisplayImageSource":"steam:225840","App_RootDir":"./sven-co-op/","App_BaseDirectory":"./sven-co-op/276060/","App_WorkingDir":"276060","App_ExecutableWin":"276060\\svends.exe","App_ExecutableLinux":"276060/svends.exe","Meta_EndpointURIFormat":""}`

**Comment by IceOfWraith** [comment]
I should note for others that come across this issue, It's as simple to fix as editing the .kvp file and replacing that one instance of the server AppID with the correct client info.

**Comment by PhonicUK** [comment]
Fixed in latest build.
