### ISSUE TITLE
Assetto Corsa Server for AMP

### ISSUE THREAD

**Issue by OmegaZ1Z** [CubeCoders/AMPTemplates#142]
# Module Request

Hi there, pls create a template for this game thanks.
Servers configs are done through an file.

## Game Information:

Game Title: Assetto corsa
How to obtain: https://store.steampowered.com/app/244210/Assetto_Corsa/
Server application: Assetto Corsa dedicated server , APP ID: 302550
Suppoted OSs: Windows
Supports RCON/Console input? No

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by jasperfirecai2** [comment]
server app ID is for https://store.steampowered.com/app/805550/Assetto_Corsa_Competizione/ Assetto_Corsa_Competizione
Assetto Corsa is the older 2014 version. 
Just to clear up any confusion

**Comment by OmegaZ1Z** [comment]
> server app ID is for https://store.steampowered.com/app/805550/Assetto_Corsa_Competizione/
> 
> Assetto Corsa is the older 2014 version. Just to clear up any confusion

Sorry my fault, is corrected now.

**Comment by Greelan** [comment]
I will have a look at this. When I last looked at it, the server setup wouldn’t work well with AMP generic, but it seems now that they have a more sane dedicated server setup. I will put something together this weekend for testing

**Comment by Greelan** [comment]
Just to clarify, I am looking at Assetto Corsa Competizione. That dedicated server setup seems sane. I think the older Assetta Corsa is the one that won’t work well with AMP generic

**Comment by OmegaZ1Z** [comment]
Why dont you think so?
[server_cfg.txt](https://github.com/CubeCoders/AMPTemplates/files/8882553/server_cfg.txt)
Heres a server config for example... minecraft also functions like this or not? through an config file

**Comment by Greelan** [comment]
From what I’ve read, you need to install the game and then copy server files over from somewhere. That’s the issue, not the config files. Happy for you to correct me if I am wrong. The newer version (Competizione) has its own dedicated server download, separate to the game download

**Comment by OmegaZ1Z** [comment]
yes this also has an own DL for the server standalone thats the APP ID I wrote b4 thats the server...
And most people that work with this game already know it... so that wouldnt be the problem. And if, we could simply write an short info box or somethin... im sure something like that is doable.

**Comment by Greelan** [comment]
So, just so I understand - is the dedicated server download all that is needed to run the dedicated server, or does it also need the game downloaded? If it needs both, where do the server files need to be placed? The whole idea of AMP is to automate this stuff, so it needs to be doable without user intervention or instructions

**Comment by OmegaZ1Z** [comment]
nope you only need the server download no need for copying files (to start) 
to customize yes, then you need to copy/edit files.

**Comment by Greelan** [comment]
OK, I will check it out. Is there a guide to all the settings in server_cfg?

**Comment by Greelan** [comment]
Nvm, found the manual on the forum, although it looks pretty old

**Comment by Greelan** [comment]
Initial template [here](https://github.com/CubeCoders/AMPTemplates/pull/143).

Interested in feedback.

**Comment by Greelan** [comment]
BTW, would be helpful to get console output when players join and leave the server (and chat if that is possible), so that the regex in AMP can be finalised.

**Comment by OmegaZ1Z** [comment]
Yes will test as soon as its available.
Also other thing here: There is also a community modded version of this server 
https://github.com/compujuckel/AssettoServer
Do I need to make a new template request for it alone orrrrr can we manage that here... since its also Assetto corsa.

**Comment by Greelan** [comment]
It's available now :)

1. Download the files from GitHub by going to the pull request, click each file, right click the "raw" button, and Save As.
2. Place the kvp and json files in your AMP datastore under (ADS Instance Name)/Plugins/ADSModule/GenericTemplates
3. Restart ADS.
4. The game server can be selected like any other when creating a new instance.

The Assetto Server probably needs to be its own template, from a quick look at the repo.

**Comment by OmegaZ1Z** [comment]
![ssadasdas](https://user-images.githubusercontent.com/75405919/173191687-b466e3e2-04c1-4dbb-a450-b92266197bda.JPG)
works :) now just need to adjust the standard ports...

**Comment by Greelan** [comment]
Great. Any other settings that you'd think would be useful in the UI?

Also could you give the full log lines for user join/leave/chat, so I can complete the regex.

I'd do it myself expect my windows VM is not up to running the game.
