### ISSUE TITLE
Legacy games need changes on startup parameters 

### ISSUE THREAD

**Issue by xLeviNx** [CubeCoders/AMPTemplates#158]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: Legacy Games in Source Module
Suppoted OSs: Windows/Linux
Supports RCON/Console input? No

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

As mentioned in discord, the legacy games found in the scrdsmodule operate differently and need a few of the startup parameters removed, in order to work a bit more efficiently.

The following should be removed:
-usercon (not used in legacy games)
+sv_pure (not used in legacy games)

The following needs to be edited
+hostname (should not have a + next to it)
sv_downloadurl "not a startup command needed. Should be defined in server configuration file, as it would make it easier"

Will throw more suggestions if needed in the future

**Comment by IceOfWraith** [comment]
Apologies for not catching this sooner. This should be posted to the main repo since it's not using the Generic module. Mike will have to address it in the proprietary code.
