### ISSUE TITLE
Cryofall

### ISSUE THREAD

**Issue by Skyfuller1303** [CubeCoders/AMPTemplates#176]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: Cryofall
How to obtain: https://wiki.atomictorch.com/CryoFall/Server/Setup
Suppoted OSs: Linux, Windows
Supports RCON/Console input?
Yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
#494
