### ISSUE TITLE
Night of the Dead Request

### ISSUE THREAD

**Issue by xTz11** [CubeCoders/AMPTemplates#189]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/
I have  allready trying  to create some files but instances dont run.. Thx for helping us.

## Game Information:

Game Title: Night of the Dead
How to obtain: https://store.steampowered.com/app/1377380/Night_of_the_Dead
How to install: https://steamcommunity.com/app/1377380/discussions/0/2849047119419572824/
Suppoted OSs: Windows
Supports RCON/Console input? yes

## I confirm:

- [ x] that I have searched for an existing module request for this application.
- [ x] that the server is an official server distributed by the games publishers/developers.
- [ x] that the server is available to the general public.
- [x ] that the server can be run headless (without a GUI).
- [ x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/223
