### ISSUE TITLE
Call Of Duty Modern Warfare 3 - Steam

### ISSUE THREAD

**Issue by Iceymidgit** [CubeCoders/AMPTemplates#190]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:
Call Of Duty Modern Warfare 3

Game Title:
How to obtain: https://store.steampowered.com/app/115300/Call_of_Duty_Modern_Warfare_3/
Suppoted OSs: Windows - Linux ( Wine )
Supports RCON/Console input? Yes

i haven't tested config due to controller issues
[COD-MW3.zip](https://github.com/CubeCoders/AMPTemplates/files/9553577/COD-MW3.zip)
## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [ ] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
I've got a draft template almost there and will share shortly

**Comment by Iceymidgit** [comment]
i did make one just can't test due to controller issues with AMP it is linked above

**Comment by Greelan** [comment]
Saw that. It's a start but has a few issues xD

**Comment by Greelan** [comment]
Draft template is in my dev repo `Greelan/AMPTemplates:dev`

Instructions in the AMP Discord channel to use it: https://discord.com/channels/266012086423912458/671396391804731405/1001660483805401178

I've only tested on Linux so far - it seems to start the server OK (netstat and htop show the ports and process) but I don't have the client to connect with. And there is no console output in AMP.

**Comment by IceOfWraith** [comment]
This was merged into the official repo.
https://github.com/CubeCoders/AMPTemplates/pull/193
