### ISSUE TITLE
Euro Truck Simulator 2 & American Truck Simulator

### ISSUE THREAD

**Issue by fabricenl** [CubeCoders/AMPTemplates#248]
# Module Request

https://blog.scssoft.com/2022/12/convoy-dedicated-servers-support.html for Linux
Running into issues with that it wants to use a weird location for config storage.. not working at all for me. Doing it manually in linux also gives issues as it won't start the 2nd server and no errors >.<

## Game Information:

Game Title: Euro Truck Simulator 2 & American Truck Simulator.
How to obtain: https://blog.scssoft.com/2022/12/convoy-dedicated-servers-support.html
Suppoted OSs: Windows + Linux (I only need linux(
Supports RCON/Console input? Yes but currently not available yet, ports seem to be there.

## I confirm:

- [x ] that I have searched for an existing module request for this application.
- [x ] that the server is an official server distributed by the games publishers/developers.
- [x ] that the server is available to the general public.
- [x ] that the server can be run headless (without a GUI).
- [x ] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by IceOfWraith** [comment]
For anyone looking to do this one, there is a read me that comes with the server download which has instructions, based on that link.

I'm not claiming it, but I'll attempt it Saturday if nobody else has by then.

**Comment by fabricenl** [comment]
I can help with explaining how it works. Have it running on windows and linux now. The-Fabby#8018 discord

**Comment by IceOfWraith** [comment]
Link to the files they shared. As noted there, it seems these may need to be created directly from each server owner's copy of the game to be unique. Going to need to do more digging though. And the documentation is pretty sparse so far.

https://discord.com/channels/266012086423912458/671396391804731405/1050564345131700284

**Comment by fabricenl** [comment]
Yeah so when doing this without AMP there's the issue that I cannot start up a second. 
Attempted so far
- Use provided commands will not allow to set a different folder. 
- using multiple installs of the server will not help, neither in combination with above

It is the first release and they said a lot more will be added including raise in player limits. So what ain't possible now might be in the near future.

**Comment by IceOfWraith** [comment]
Did you create different export files per server? I'm assuming that will be a factor as well.

**Comment by fabricenl** [comment]
> Did you create different export files per server? I'm assuming that will be a factor as well.

Yep I did, but the biggest problem here seems to be that both servers will use the same location for the export files and config. You can set the custom export files and config but it has to share the .dat file and log files and maybe more. My guess is that is where its tripping.

**Comment by Greelan** [comment]
There is a suggestion that using the standard `-homedir` parameter might help avoid the server looking for the server files in the Documents dir

**Comment by fabricenl** [comment]
Okay so using homedir works but the downside is it will create a new Euro Truck Simulator 2 folder to put everything in, but it is possible.

**Comment by fabricenl** [comment]
So while this works, it will not launch the 2nd server still. For quick testing I used windows.  Still a empty black command screen then after a bit closes. No errors or logs :(
- Different installation folders
- Different document folders
- Different ports

**Comment by Badoyz** [comment]
I do have ETS2 and ATS for Linux. I haven't gotten around to trying to make it work with windows yet. I'm also not sure how to make AMP work with the games configs, but you can create and instance and install the game. When you click start it will create the home directory inside the instance folder so then you just stop the server, open File Manager and drag and drop your files in. I have two ATS servers running off my AMP panel.

[ATS_AMPTemplate.zip](https://github.com/CubeCoders/AMPTemplates/files/10660256/ATS_AMPTemplate.zip)
[ETS2_AMPTemplate.zip](https://github.com/CubeCoders/AMPTemplates/files/10660258/ETS2_AMPTemplate.zip)

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/332
