### ISSUE TITLE
Icarus Linux Support

### ISSUE THREAD

**Issue by skynett81** [CubeCoders/AMPTemplates#255]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: Icarus
How to obtain: https://github.com/RocketWerkz/IcarusDedicatedServer

Suppoted OSs: Windows but can run under linux too 
Take a lock at : https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/icarus

runs the Windows build of the server via Wine64

Server Steam App ID
2089300

Client Steam App ID
1149460

Supports RCON/Console input? yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by skynett81** [comment]
well the stuff i linked to does work on linux , i do run my controller and target on debian 11 , i cant install the icarus sens its only supports windows

and yes i did try  Configuration->Instance Deployment

![2022-12-20 03_04_16-AMP - Application Management Panel - Opera](https://user-images.githubusercontent.com/9619727/208563961-441d0c2e-f53b-4452-88ae-01df8ef7ca5b.png)

**Comment by IceOfWraith** [comment]
I've updated the post to reflect that you were specifically looking for Linux.

**Comment by Greelan** [comment]
Dev template now up to date
