### ISSUE TITLE
New Valheim (Merged) Configuration does not install BepInEx after update

### ISSUE THREAD

**Issue by AshDevFr** [CubeCoders/AMPTemplates#258]
Hi, 

I have been following this PR #241 for some time and now that it was merged I tried it out with my existing server.
I wanted to be able to add only `BepInEx` and not `Valheim Plus`.

It does not seem to have any impact when I enable `Install BepInEx` in `SteamCMD and Updates`. 
Is there anything to do to make it work with an existing config or should I create a new server?

Thanks

**Comment by IceOfWraith** [comment]
TLDR it's best to make a new instance.

If you're coming from an old version of the template, you have to right click and Update the instance, as well as right click and Refresh it. These two things are needed to get all the stuff (I believe). It's kind of a funky setup still to get new versions. But a new instance should have all of this done for you.

**Comment by AshDevFr** [comment]
I tried the `update` and `refresh` already and a couple of time after. It did not work.

I don't mind recreating the server, I was mostly curious if it was possible to simply update

**Comment by IceOfWraith** [comment]
Just to be sure, You can right click the instance and View Logs to make sure it's not something else.

**Comment by AshDevFr** [comment]
Hum good point. Sorry I already killled and recreated the instance.
