### ISSUE TITLE
Project Zomboid: Server runs on port 27015 after every update

### ISSUE THREAD

**Issue by pandalion98** [CubeCoders/AMPTemplates#282]
Despite being configured properly, the server runs on port 27015 after every update. Default port is 16261.

To remedy the problem, I have to go to the instances list, click "Edit Ports" for the Project Zomboid instance, and click "Save Changes" without changing anything.

It would be cool if I don't have to do the above after every update. My server goes down for long periods since the port changes without me noticing (The problem can only be seen in the instance console `Clients should use 27015 port for connections`)

**Comment by Greelan** [comment]
Very odd behaviour I have not seen before. Under Configuration->Networking->Port Assignment Mode, I suggest you set it to “Allow all except excluded”. The PZ ports are not in AMP’s default application port ranges, which *might* have something to do with what you are seeing.

**Comment by IceOfWraith** [comment]
Closing this due to lack of response and an isolated issue.
