### ISSUE TITLE
[Server Request]: Operation: Harsh Doorstop

### ISSUE THREAD

**Issue by branti1** [CubeCoders/AMPTemplates#298]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Steam Appid: 950900

https://docs.google.com/document/d/e/2PACX-1vTGjYAEqM6UTfpST_W-gnA0sDjrddks69vtrd_bkkhcwJppd1CrdQzKQM368WcTkmehIXYSK7w_i4zs/pub

guide is for windows. 

Game Title: Operation: Harsh Doorstop [UE4.25]
How to obtain: https://steamdb.info/app/950900/)
Suppoted OSs: windows, linux
Supports RCON/Console input? yes

## I confirm:
- [x ] that I have searched for an existing module request for this application.
- [x ] that the server is an official server distributed by the games publishers/developers.
- [x ] that the server is available to the general public.
- [x ] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/462
