### ISSUE TITLE
Minetest module

### ISSUE THREAD

**Issue by skull4L** [CubeCoders/AMPTemplates#345]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: Minetest
How to obtain: https://gitlab.com/sztest/minetestserver (see https://wiki.minetest.net/Setting_up_a_server#Obtaining_a_server_binary for specific information)
Suppoted OSs: Linux, Windows
Supports RCON/Console input? Most likely

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by Greelan** [comment]
I've got a draft template in `Greelan/AMPTemplates:dev`.

Be interested in feedback.

Note that on Linux it uses the community AppImage (https://github.com/An0n3m0us/Minetest-AppImages). It seems well-established and reliable but interested in thoughts.
