### ISSUE TITLE
request for new game addition Smalland: Survive the Wilds 

### ISSUE THREAD

**Issue by regchanuk** [CubeCoders/AMPTemplates#361]
# Module Request

Note:  to be added when they release server side  

## Game Information:

Game Title: Smalland: Survive the Wilds   dedicated server

How to obtain:  still to be determined most likely steam
https://store.steampowered.com/app/768200/Smalland_Survive_the_Wilds/
https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/clans//31398346/62bf85819f5022e2fed9516a166609bc2f5bc8ca.png
picture of roadmap 
Suppoted OSs: TBC
Supports RCON/Console input? TBC

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Seems dedicated servers will only released with v1.0, so likely a long way off.

https://steamcommunity.com/app/768200/discussions/0/3787002916498913012/

**Comment by regchanuk** [comment]
i will keep an eye o this and will update this please keep this active / paused state

**Comment by fartboner** [comment]
https://store.steampowered.com/news/app/768200/view/3893988945397359022

The dedicated server files are released for linux and Windows

**Comment by Greelan** [comment]
Nice. I will look at creating a template

**Comment by Greelan** [comment]
Template in `Greelan/AMPTemplates:dev`

**Comment by Greelan** [comment]
Now merged
