### ISSUE TITLE
Error while starting V-Rising server

### ISSUE THREAD

**Issue by koskit** [CubeCoders/AMPTemplates#375]
Hello! The scenario is pretty straightforward:

- Create a default V-Rising server
- Server fails to start with error: "wine: cannot find './VRisingServer.exe'"

**Comment by gOOvER** [comment]
sounds like, you never pres update, after creation the instance

**Comment by koskit** [comment]
Hey @gOOvER , I didn't know I had to create the instance and press update as part of the creation (thought maybe the "latest" version was installed right away, but I digress),

Anyhow, I did press update (thought maybe that would solve the missing files) and still got the same thing. 

Since your comment, I re-tried it in case I missed something but still the same behavior. The instance from the main menu reports "running", but when I "manage" it, inside the instance it says " Application State: Stopped".

After stopping the instance, pressing update and restarting, the main menu still says "running" and inside the instance management page, it says "Application State: Unable to run", with the same error on console "wine: cannot find './VRisingServer.exe'".

Maybe I can try bash into the container to steamcmd the missing vrising files? Don't know a lot about preconfigured instances in this repo, so forgive my ignorance. 

Could you suggest some locations I could get more logs on what is going on inside the docker container as it starts?

**Comment by koskit** [comment]
Ok ok, tried more "update" buttons around to see if they did anything differently, and it seems the update button within the "manage instance" page seems to run the update/installation of the GameServer and download it's initial files.
Though it was a problem with the definition of the game configuration within this repository and made this issue.

Consider it closed
