### ISSUE TITLE
The ship not showing up on list even with adding "Srcds": true

### ISSUE THREAD

**Issue by jamieb452** [CubeCoders/AMPTemplates#404]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: The Ship
How to obtain: https://
Supported OSs: Linux & Windows
Supports RCON/Console input? yes

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Restart AMP?

**Comment by jamieb452** [comment]
I did, still nothing..

**Comment by jamieb452** [comment]
> Restart AMP?

Oh wait, just updated my panel since there was a minor update and its fixed, must have been a cache thing making it not show or something?
