### ISSUE TITLE
[Configuration Request] Veloren Weekly Server option

### ISSUE THREAD

**Issue by KRDucky** [CubeCoders/AMPTemplates#415]
# Module Request
Please update the Veloren server template to either give us the option in the menus to choose between Nightly and Weekly or make a separate version that is Weekly. The official Veloren server browser requirements are that the server runs on the Weekly branch. 
## Game Information:

Game Title: Veloren
How to obtain: https://Veloren.net
Suppoted OSs: Windows and Linux
Supports RCON/Console input?yes

## I confirm:

- [x ] that I have searched for an existing module request for this application.
- [x ] that the server is an official server distributed by the games publishers/developers.
- [x ] that the server is available to the general public.
- [x ] that the server can be run headless (without a GUI).
- [ x] I have already attempted to create a configuration myself using the configuration tool

**Comment by Greelan** [comment]
Can you provide a link to the weekly downloads?

My recollection tho when putting the template together was that the official servers ran on nightly.

**Comment by PhonicUK** [comment]
It's exactly the same URL but you replace "nightly" with "weekly" e.g. `https://download.veloren.net/latest/windows/x86_64/weekly`

**Comment by KRDucky** [comment]
take a gander at their official docker container: https://gitlab.com/veloren/veloren/-/blob/master/server-cli/docker-compose.yml
Also, the launcher defaults to weekly

**Comment by Greelan** [comment]
This has now been added. Right click on your instance, click Refresh Configuration. The option to select release streams should then appear under the SteamCMD and Updates menu in the instance (after you manage it). Update the server after selecting the required version

**Comment by KRDucky** [comment]
thank you
