### ISSUE TITLE
Terraria template is showing wrong endpoint port

### ISSUE THREAD

**Issue by emitlinks** [CubeCoders/AMPTemplates#425]
The new method for ports [(Terraria Updates #326)](https://github.com/CubeCoders/AMPTemplates/commit/1b631c7e5100e057e24a17b0737d7dcdafcc2f9f) used in the template make that the endpoint port and the one used for the button "connect to server" shows a different port than the one the server is using.

**Comment by Greelan** [comment]
The endpoint URI is sort of irrelevant since the server doesn't have a steam query port and that's what the steam browser would use for connecting. The URI can probably be deleted from the template (it's the default that AMP puts in)

**Comment by emitlinks** [comment]
Yes, it's just a minor visual bug since it's not really using the port it's showing, and it's not preventing connection to it.
I just think it could also be happening to other template using the "new method", and the only way to check on the real port it's using is clicking on "edit ports".

Here are screenshots showing what's happening : 
<img width="580" alt="bug-01" src="https://github.com/CubeCoders/AMPTemplates/assets/26680402/b6802ea0-323e-413c-a664-98c69624dfe9">
<img width="559" alt="bug-02" src="https://github.com/CubeCoders/AMPTemplates/assets/26680402/f277467d-f813-4a8b-96db-56d860085e02">
<img width="503" alt="bug-03" src="https://github.com/CubeCoders/AMPTemplates/assets/26680402/7c640471-3560-452e-bc66-812d73a9e54b">

Both test1 and test2 are using different ports, but they still show that they are using 27015 unless you go to edit ports.

**Comment by Greelan** [comment]
Whether it happens on other templates depends how they are set up

**Comment by Greelan** [comment]
This is not the place for bug reporting
