### ISSUE TITLE
Barotrauma file: clientpermissions.xml keeps resetting on update

### ISSUE THREAD

**Issue by boyteulings** [CubeCoders/AMPTemplates#451]
I'm trying to host a Barotrauma server, but I can't add any admins as the clientpermissions.xml file keeps being reset every time I click the "update" button in the AMP control panel for the server. It seems like updates also update the clientpermissions.xml file, which seems unnecessary.

**Comment by Greelan** [comment]
That's a Steam/Barotrauma dev issue. The file is not marked as "user config" on steam so Steam validates and redownloads the default on each update

**Comment by boyteulings** [comment]
Got it, thanks. Suppose I should go over and ask them to change it :)
