### ISSUE TITLE
Game Open World

### ISSUE THREAD

**Issue by jakub961241** [CubeCoders/AMPTemplates#458]
Module Request
Note: Please try setting up a configuration yourself before raising an issue to request a configuration: https://config.getamp.sh/
***There is a newer beta version available at https://config.iceofwraith.com/

Game Information:
Game Title: Open World
How to obtain: 
Windows Current - https://github.com/D12-Dev/OpenWorld/releases/download/v1.0.4/win-x64.zip
Linux Current - https://github.com/D12-Dev/OpenWorld/releases/download/v1.0.4/linux-x64.zip
 (the Linux server is easier to setup and more reliable)

Installation guidance (for dependencies, etc) can be found at: https://openworldhelp.fandom.com/wiki/Creating_a_server

Suppoted OSs: Windows & Linux
Supports RCON/Console input? No?

I have gotten it working on one of my server, through some manual setup, but it has dependencies that it would be better to have contained to a docker instance instead of installing everywhere and I could not get that working.

I confirm:
 that I have searched for an existing module request for this application.
 that the server is an official server distributed by the games publishers/developers.
 that the server is available to the general public.
 that the server can be run headless (without a GUI).
 I have already attempted to create a configuration myself using the configuration tool
 that my checkboxes above look like the one on the left (remove this line when done)

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/459

**Comment by IceOfWraith** [comment]
Greelan has added this now.
