### ISSUE TITLE
Rust Carbon module

### ISSUE THREAD

**Issue by jakub961241** [CubeCoders/AMPTemplates#460]
Module Request
Note: Please try setting up a configuration yourself before raising an issue to request a configuration: https://config.getamp.sh/

Game Information:
Game Title: Rust Carbon module
How to obtain: https://github.com/CarbonCommunity/Carbon/releases (see https://docs.carbonmod.gg/docs/ for specific information)
Suppoted OSs: Linux, Windows
Supports RCON/Console input? Most likely

I confirm:
 that I have searched for an existing module request for this application.
 that the server is an official server distributed by the games publishers/developers.
 that the server is available to the general public.
 that the server can be run headless (without a GUI).
 I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by Greelan** [comment]
This is not the place to request features for official modules
