### ISSUE TITLE
Astrto Colony

### ISSUE THREAD

**Issue by adamcirillo** [CubeCoders/AMPTemplates#493]
# Module Request

## Game Information:

Game Title: Astro Colony
How to obtain: [Astro Colony Dedicated Server Setup](https://docs.google.com/document/d/11sC1F2HdSymO44Hklg3nfrO5D66YIs7rEUrGV1GjpDM/edit#heading=h.nj23sjpj5u97)
Suppoted OSs: Windows
Supports RCON/Console input? Not Sure

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

**Comment by Greelan** [comment]
Not aware of the game having dedicated servers

**Comment by Greelan** [comment]
I've created a draft in `Greelan/AMPTemplates:dev`, but wow, this server is janky. A bunch of stuff does not seem to work?

**Comment by Greelan** [comment]
Afaik, the multihome argument has not been implemented for this server. In any event, binding to 0.0.0.0 is fine. The issue with the server list is that, last time I checked a couple of weeks ago, it only shows around 60 servers at one time, and doesn't have a search/filter function. The dev has said he will increase the number to 150 or 200 and add the search/filter function, making it easier to find your server.

Make sure you have forwarded the query port.
