### ISSUE TITLE
New Game Request : Ark Survival Ascended

### ISSUE THREAD

**Issue by gjm19761** [CubeCoders/AMPTemplates#534]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Ark Survival Ascensded
How to obtain: https://store.steampowered.com/app/2399830/ARK_Survival_Ascended/
Suppoted OSs: Windows, XBOx PS5
Supports RCON/Console input? RCon

## I confirm:

- [x ] that I have searched for an existing module request for this application.
- [ x] that the server is an official server distributed by the games publishers/developers.
- [ x] that the server is available to the general public.
- [ x] that the server can be run headless (without a GUI).
- [ x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Already in AMP xD
