### ISSUE TITLE
LS 22/Farming Simulator 22 Server

### ISSUE THREAD

**Issue by GerDeathHunter** [CubeCoders/AMPTemplates#54]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title:Landwirdschafts Simulator22 / Farming Simulator 22
How to obtain: https://
Suppoted OSs:OS | Linux
Platform | Ubuntu 20.04.3 LTS
Supports RCON/Console input? I do not know

I have to admit that I have no idea what to write here. So I am writing a little text about it.

I would like to play LS 22/Farming Simulator 22 with a couple friends. However, I am not able to create a module myself in the AMP. So I hope that someone can help me here.

hp Since I don't speak English, I translated everything with google translate.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [ ] that the server is available to the general public.
- [ ] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by Shinynecrid** [comment]
Adding the installation PDF for future reference on the development of this module.

[dedicatedServer_en.pdf](https://github.com/CubeCoders/AMPTemplates/files/7964353/dedicatedServer_en.pdf)

**Comment by ApertureDevelopment** [comment]
Attaching what I said earlier here too

I see a few issues with any FS Dedicated Server
1. You can only download the server application from the website when you have a legit key to enter first, this could cause issues with AMP downloading
2. The server application seems to always save to %userdir%/Documents/My Games I am trying to find out if there is a undocumented exe parameter to set it to another directory
3. Starting the exe file manually using startup parameters does not seem to actually start the gameserver, which is a big issue. Again there could be hidden startup parameters but if there are they are very well hidden
4. Currently ( as of the current knowledge ) I think AMP is only able to provision the base of FSDS, meaning that it would only run the dedicatedServer.exe file and then redirect the user to the official Farming Simulator webpanel that is shipped with the server. ( which basically every hoster seems to do )
5. For the server to actually work you need to run the game first once and enter your license key. There is no CLI or CFG way of entering the key

**Comment by ApertureDevelopment** [comment]
Also to update the initial issue:

How to obtain: https://eshop.giants-software.com/downloads.php
Supported OSes: Windows Only ( does not work with Wine or Proton ) 
Supports RCON/Console input? No

**Comment by IceOfWraith** [comment]
As we discussed in Discord, all these steps are doable, except for one. The game server on Steam doesn't ask for a separate key to startup, but does launch Steam as the verification. This is not something AMP can facilitate at this time. @ApertureDevelopment has agreed to look into ways around this, but it's very likely that isn't possible without breaking the game or Steam's ToS.

My point is, until Giants Software fixes their dedicated server practices (which don't follow the methods of any other game) this one probably can't be automated fully. An "unofficial" generic config may be possible though that halfway accomplishes automation.

**Comment by PhonicUK** [comment]
This isn't possible right now due to the reliance on the Steam desktop application. The developers would need to make an actual, proper dedicated server. Closing for now but it can be re-visited if the developers improve the server.

**Comment by mattyou1985** [comment]
eney update to this or is it still a no fix for amp ?

**Comment by IceOfWraith** [comment]
We've overcome all the issues other than activation. The devs need to allow an automated/command line method to activate for it to work on server software like AMP.

**Comment by Greelan** [comment]
I asked in their discord, but the post gets quickly buried in general chat
