### ISSUE TITLE
New Server Request: Subsistence

### ISSUE THREAD

**Issue by clefebvre81** [CubeCoders/AMPTemplates#576]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Subsistence Dedicated Server
How to obtain: https://steamcommunity.com/sharedfiles/filedetails/?id=2201638184
Suppoted OSs: Windows
Supports RCON/Console input?

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
There's a template in my dev branch: `Greelan/AMPTemplates:dev`.

The devs have created a Unreal Engine server and made it run like crap. No console output or input on Windows, and so far refuses to run under Wine on Linux.

**Comment by Greelan** [comment]
Working on Linux now.

Still no console output on either platform.

**Comment by Greelan** [comment]
Server runs, still no console output
