### ISSUE TITLE
New Template Request for Palworld

### ISSUE THREAD

**Issue by rdaniels0906** [CubeCoders/AMPTemplates#600]
Would someone be willing to make a template for Palworld please? It supports Windows and Linux, uses SteamCMD and the publisher has pretty decent documentation here: https://tech.palworldgame.com/dedicated-server-guide#settings

**Comment by miguemely** [comment]
@rdaniels0906 It is currently in progress. @Greelan is currently writing the template right now.

**Comment by Dolac84** [comment]
I was just coming to put in a request myself, thank you @rdaniels0906 for the post... @Greelan thank you for workin on a template!

**Comment by Vlandarr** [comment]
Also want to toss a big tanks to @Greelan for working on this!

**Comment by akusei** [comment]
This is great! I gave it a try and rcon is working but I'm unable to actually connect to the server in-game. I haven't changed any settings from their defaults. I'm wondering if this is an issue with the template or a bug in the game

**Comment by Snake4life** [comment]
does anybody know what 'Enable Multiplayer' aka. 'bIsMultiplay' exactly does? It's set to false by default. I suspect it adds the server to the community server list?

**Comment by Greelan** [comment]
No idea, not documented (except that it has nothing to do with the community list).

I suspect this config has settings that are also used by the game client multiplayer mode.

Over time once things become clearer, they will be removed from the AMP UI if not needed.
