### ISSUE TITLE
Day of Dragons [Legacy] Support

### ISSUE THREAD

**Issue by sanegaming** [CubeCoders/AMPTemplates#608]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Day of Dragons [Legacy branch]
How to obtain: [Steam](https://store.steampowered.com/app/1088090/Day_of_Dragons/)
Suppoted OSs: Linux/Windows
Supports RCON/Console input? Y

## I confirm:
- [ x] that I have searched for an existing module request for this application.
- [ x] that the server is an official server distributed by the games publishers/developers.
- [ x] that the server is available to the general public.
- [ x] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool

**Comment by Greelan** [comment]
What exactly are you after? Day of Dragons is already included

**Comment by Greelan** [comment]
And the "legacy" beta branch can be selected under SteamCMD and Updates

**Comment by sanegaming** [comment]
Apologies, I Missed that option. Closing!
