### ISSUE TITLE
Openrct2

### ISSUE THREAD

**Issue by binarygeek119** [CubeCoders/AMPTemplates#63]
# Module Request

Openrct2
https://openrct2.org/

multiplayer documents 
https://docs.openrct2.io/en/latest/playing/multiplayer/index.html

## Game Information:

Game Title:Openrct2 - rollercoaster tycoon 2 open source 
How to obtain: https:// not sure "host" i think
Suppoted OSs: windows linux mac android
Supports RCON/Console input? unknown

## I confirm:

- [X] that I have searched for an existing module request for this application.
- [X] that the server is an official server distributed by the games publishers/developers.
- [X] that the server is available to the general public.
- [X] that the server can be run headless (without a GUI).
- [X] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by IceOfWraith** [comment]
I've looked into it. I believe this is definitely something that can be implemented into AMP. I haven't fully tested, but a quick attempt at starting a headless server appears it might not even need the game files to be included. If so, this would be an extremely easy one to create. If someone doesn't pick this up before I have free time then I'll attempt to tackle it.

Further reading for others:
[Headless Server Guide](https://docs.openrct2.io/en/latest/playing/multiplayer/index.html)

**Comment by Abchrisabc** [comment]
> I've looked into it. I believe this is definitely something that can be implemented into AMP. I haven't fully tested, but a quick attempt at starting a headless server appears it might not even need the game files to be included. If so, this would be an extremely easy one to create. If someone doesn't pick this up before I have free time then I'll attempt to tackle it.
> 
> Further reading for others:
> [Headless Server Guide](https://docs.openrct2.io/en/latest/playing/multiplayer/index.html)

It indeed does not require the game files for the server as I have seen.

I have been doing a little bit of configuring and testing, I just need to figure out some issues that I am having with pointing AMP to the right directories as the tar.gz for Linux has a single folder and within that folder are all the files.

**Comment by IceOfWraith** [comment]
Usuay that's your App.WorkingDirectory in the kvp file. It is where AMP will "cd" to in order to run things. Feel free to discuss here, but we also are extremely active discussing development in Discord.

**Comment by IceOfWraith** [comment]
@Abchrisabc have you gotten any progress made on this one? If not, I'll move it back to "Available to be picked up".

**Comment by JonathanArendt** [comment]
@IceOfWraith If there has not been any further steps taken, I don't see an fork linked, I would be more than willing to look into this. I have the game myself and would be interested in trying to make this work.

**Comment by IceOfWraith** [comment]
It is still unfinished. I'll switch the status shortly to show you're working on it. Thank you!

**Comment by JonathanArendt** [comment]
You got it!

**Comment by IceOfWraith** [comment]
https://github.com/CubeCoders/AMPTemplates/pull/461
