### ISSUE TITLE
New Module Request Myth of Empires Dedicated server

### ISSUE THREAD

**Issue by Partiesplayin** [CubeCoders/AMPTemplates#640]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Myth Of Empires
How to obtain: https://store.steampowered.com/app/1371580/Myth_of_Empires/
Supported OSs: Windows 10/11
Supports RCON/Console input? Yes

## I confirm:

- [x ] that I have searched for an existing module request for this application.
- [x ] that the server is an official server distributed by the games publishers/developers.
- [x ] that the server is available to the general public.
- [ x] that the server can be run headless (without a GUI).
- [x ] I have already attempted to create a configuration myself using the configuration tool

**Comment by Greelan** [comment]
Already in `Greelan/AMPTemplates:dev` for testing

**Comment by Partiesplayin** [comment]
How do I find it . Sorry not too familiar with navigating github . You are amazing btw.

**Comment by Greelan** [comment]
You add that to your Configuration Repos under Configuration>Instance Deployment, click Fetch Latest, then it will be appear in the instance creation dropdown under `Greelan / Myth of Empires`

You need Git installed first and added to the system PATH if on Windows

**Comment by Partiesplayin** [comment]
ok ive never used git before, how do i add it to the system path ? or how do i set it up to work to grab your repository?

**Comment by Greelan** [comment]
Just install Git, select the option to add it to PATH. That's all

**Comment by Partiesplayin** [comment]
Yeah sorry I just don't understand I guess. I installed Git I added your repository to amp but it never adds anything new.

**Comment by clefebvre81** [comment]
I can't get it to work. I keep getting 

[2024.02.24-23.42.04:361][ 0]LogWindows: Error: === Critical error: ===
[2024.02.24-23.42.04:363][ 0]LogWindows: Error:
[2024.02.24-23.42.04:364][ 0]LogWindows: Error: Fatal error: [File:Unknown] [Line: 197]
[2024.02.24-23.42.04:366][ 0]LogWindows: Error: Ran out of memory allocating 7241007104 bytes with alignment 0
[2024.02.24-23.42.04:366][ 0]LogWindows: Error:
[2024.02.24-23.42.04:367][ 0]LogWindows: Error:
[2024.02.24-23.42.04:367][ 0]LogWindows: Error:

**Comment by Greelan** [comment]
Same on my crappy VM with 16GB RAM. Wonder if it's a RAM issue or something else.

Works fine on Linux tho...

**Comment by clefebvre81** [comment]
I get the same error on my friends computer and he has a beast of a computer.

**Comment by Greelan** [comment]
It will be running - check Task Manager.

If you want a console opened, add `-log` to the startup arguments.

**Comment by MonkeyOnKeyboard** [comment]
@Greelan good morning from germany. its posible to help you with the Template for Myth of Emprires? Because i need it to. 
ive testet you dev template. but a lot of config stuff are missing. and its not able to load an custom server config

**Comment by Greelan** [comment]
It's not feasible to add all 200 settings. The server only uses command line args. The template though allows you to add additional args as needed. I can't really help the bad way the server devs have set up this server, I'm afraid

**Comment by MonkeyOnKeyboard** [comment]
did you have a list of all comments, so i would add all. if ist possible. also if i save ingame server settings as admin. the server dont save it right. after reboot server the setting are gone....

**Comment by MonkeyOnKeyboard** [comment]
> It's not feasible to add all 200 settings. The server only uses command line args. The template though allows you to add additional args as needed. I can't really help the bad way the server devs have set up this server, I'm afraid

And how can i Add the args in the Template?

**Comment by Greelan** [comment]
![image](https://github.com/CubeCoders/AMPTemplates/assets/53196309/28215150-1d03-43b5-9a87-7bd85cf97e59)

**Comment by MonkeyOnKeyboard** [comment]
if i use the template generator is there an example for MOE?

**Comment by MonkeyOnKeyboard** [comment]
how can i import my modded configmanifest.json into the template?

**Comment by Greelan** [comment]
Paste it

**Comment by MonkeyOnKeyboard** [comment]
where?

**Comment by MonkeyOnKeyboard** [comment]
ive past it in amp but no changes. how can i reload instance?

**Comment by MonkeyOnKeyboard** [comment]
@Greelan would you like the modded  configmanifest.json for Myth. Ive done. all settings inthere

**Comment by Greelan** [comment]
Sure, if it's robust, send it over. Needs to have good descriptions, right value types, value ranges if applicable, etc. We don't do things by halves lol

**Comment by clefebvre81** [comment]
Is this working in Windows yet?

**Comment by Greelan** [comment]
Yes
