### ISSUE TITLE
Home Assistant integration 

### ISSUE THREAD

**Issue by DwinkBexon** [CubeCoders/AMPTemplates#647]
Please can a Home Assistant integration be look into, showing server stats such as user count, map, CPU usage, RAM usage, ping etc.

Would be helpful for those running HA alongside AMP

Thank you.

**Comment by p0t4t0sandwich** [comment]
This is the wrong repo for this sort of thing, AMPTemplates is just for requesting apps/game templates for AMP.
Though you can use AMP's API to integrate with pretty much anything, you could probably hook up HA to poll resources using the AMP API.
There's some docs/useful links regarding the API here: <https://github.com/p0t4t0sandwich/ampapi-spec?tab=readme-ov-file#amp-api-and-library-info>
Though for a project like this you'd probably use the stats wrapper I wrote: <https://github.com/p0t4t0sandwich/ampapi-stats-wrapper>

**Comment by DwinkBexon** [comment]
> This is the wrong repo for this sort of thing, AMPTemplates is just for requesting apps/game templates that you run inside AMP. Though you can use AMP's API to integrate with pretty much anything, you could probably hook up HA to poll resources using the AMP API. There's some docs/useful links regarding the API here: https://github.com/p0t4t0sandwich/ampapi-spec?tab=readme-ov-file#amp-api-and-library-info Though for a project like this you'd probably use the stats wrapper I wrote (simplifies the API's auth setup into a simple REST API): https://github.com/p0t4t0sandwich/ampapi-stats-wrapper

Many thanks for your quick reply! I shall look into these.

**Comment by PhonicUK** [comment]
Closed for wrong repo.

**Comment by barrelltitor** [comment]
@DwinkBexon if you're not in a hurry I could probably do something like this via MQTT by the end of the month. Watch this repo for updates, it's empty now https://github.com/barrelltitor/amp-homeassistant
