### ISSUE TITLE
Enshrouded template - Backup creation broken

### ISSUE THREAD

**Issue by gymnae** [CubeCoders/AMPTemplates#675]
Per Bug report in [Discourse](https://discourse.cubecoders.com/t/configuration-with-enshrouded-cannot-create-manual-or-automated-backup-from-instance/9632), it is currently not possible to create a manual or schedule driven backup. 

We couldn't find indicators in the log to the reason for this.

**Comment by Greelan** [comment]
Wow, dude, I give you help, and that's the attitude I get? Nice

**Comment by gymnae** [comment]
> Wow, dude, I give you help, and that's the attitude I get? Nice

Your comment, as written here in github was not helpful. I see hat in Discourse you written it differently, pointing that certain data should be exclude,  and that made it more clear. 

And the note is targeted towards CubeCoders: If the issue is related to a fixed file size limit, then the backup system should notify the user. Instance admins might be pointyclicky admins and won't know what's wrong. A notification helps. 

Coming back to what you wrote in Discourse. Should I use the context menu in the File manager to exclude folders and files? If so, tried that, especially that mentioned 12GB server file. The backup still fails without a log entry, after it "collects files for backup"

**Comment by IceOfWraith** [comment]
AMP has a Smart Backup Exclusions system for reasons like this. It is turnkey. Search for that in the instance and enable it then see how your backup goes.

**Comment by gymnae** [comment]
I had this system active. Yet AMP won't create a backup for this template. 
Just tried with factorio - no problem creating a backup with no changes to the config. 

I checked the permissions of my install, they also appear fine.

**Comment by gymnae** [comment]
I gave pterodactyl a try and with it backups work fine, servers too. I’ll see if I’ll migrate fully
