### ISSUE TITLE
stationeers.kvp doesn't work anymore with AMP  2.5 - 20240315.1

### ISSUE THREAD

**Issue by HesseMTK** [CubeCoders/AMPTemplates#679]
System Information
Field	Value
Operating System	Windows - Windows Server 2019 on x86_64
Product	AMP ‘Callisto’ v2.5.0.0 (Mainline)
Virtualization	Xen
Application	Stationeers
Module	GenericModule
Running in Container	No
Current State	Stopped
Problem Description
Issue
Server instance started with the “Stationeers” preset. Steam CMD installation is successful. Server stops in step Update 2/4 - Start Server. Restarting and reinstalling does not solve the problem

Reproduction Steps
New Instance - Stationeers
Stuck on Start Server
Instance freeze on Start Server

`22:12:16
CPID: 3084
Redirecting stderr to 'C:\AMPDatastore\Instances\Stationeers01\stationeers\logs\stderr.txt'
Logging directory: 'C:\AMPDatastore\Instances\Stationeers01\stationeers/logs'
[ 0%] Checking for available updates...
22:12:17
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK
force_install_dir "600760"
22:12:20
Connecting anonymously to Steam Public...OK
22:12:22
Waiting for client config...OK
Waiting for user info...OK
app_update 600760 -beta public validate
Update state (0x5) verifying install, progress: 32.28 (9431123 / 29212173)
22:12:24
Update state (0x5) verifying install, progress: 11.39 (311836471 / 2737550962)
22:12:26
Update state (0x5) verifying install, progress: 32.19 (881104145 / 2737550962)
22:12:28
Update state (0x5) verifying install, progress: 46.32 (1268024379 / 2737550962)
22:12:30
Update state (0x5) verifying install, progress: 67.20 (1839628581 / 2737550962)
22:12:32
Update state (0x5) verifying install, progress: 86.73 (2374297516 / 2737550962)
22:12:33
Success! App '600760' fully installed.
quit`

Start instance not possible

**Comment by HesseMTK** [comment]
@IceOfWraith

**Comment by Greelan** [comment]
AMP bug. Workaround: stop your instance, edit GenericModule.kvp in the instance datastore, and add `App.HasSuccessfullyUpdatedAtLeastOnce=True`
