### ISSUE TITLE
Request to add bdsx server software for minecraft

### ISSUE THREAD

**Issue by thebirchtree** [CubeCoders/AMPTemplates#698]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Minecraft BDSX Server with node js
How to obtain: https://github.com/bdsx/bdsx
Suppoted OSs: windows, linux
Supports RCON/Console input? yes console not sure for rcon 
## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Regrettably BDSX does not work as a child process so cannot run in AMP. Apparently a known issue with the components it is made of

**Comment by Greelan** [comment]
And now the dev has archived the project. So this is not viable
