### ISSUE TITLE
Pixark and Stardew valley

### ISSUE THREAD

**Issue by xshortbusx** [CubeCoders/AMPTemplates#724]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title:
How to obtain: https://
Suppoted OSs:
Supports RCON/Console input?

## I confirm:

- [ ] that I have searched for an existing module request for this application.
- [ ] that the server is an official server distributed by the games publishers/developers.
- [ ] that the server is available to the general public.
- [ ] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by p0t4t0sandwich** [comment]
There's already a request for Stardew Valley, I'd also recommend going through that checklist and looking around for any useful information regarding a Pixark dedicated server.

**Comment by Greelan** [comment]
Duplicates
