### ISSUE TITLE
Abiotic Factor

### ISSUE THREAD

**Issue by BlueBackbite** [CubeCoders/AMPTemplates#758]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:
Game Title: Abiotic Factor
Early access UE5 

I've attempted to create a configuration, however I don't find them when fetching latest in AMP.
(https://github.com/BlueBackbite/Custom-AMP-Templates)
So I can't validate that I've setup the configuration correctly. 

Developer Guides: https://github.com/DFJacob/AbioticFactorDedicatedServer/wiki/Guide-‐-Quickstart

How to obtain:
Store Page: https://store.steampowered.com/app/427410/Abiotic_Factor/
Dedicated Server: https://steamdb.info/app/2857200/

Suppoted OSs: Windows
Supports RCON/Console input? Presumably.

Any feedback on what I'm doing wrong in terms of fetching custom instances would be appreciated as well.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

**Comment by BlueBackbite** [comment]
I checked the instance logs and found missing keys...
`Unable to load Generic Manifest /home/amp/.ampdata/instances/ADS01/Plugins/ADSModule/DeploymentTemplates/BlueBackbite-Custom-AMP-Templates/abiotic-factor.kvp - missing required keys: GenericModule.Meta.AppConfigId`
These don't seem to be generated by IceOfWraith's generic config gen, looking into what that value should look like...

**Comment by IceOfWraith** [comment]
Yeah that's not included yet. It just needs to be any random UUID.

**Comment by BlueBackbite** [comment]
I can run this one now, will likely turn it into a PR after putting some polish on it.

**Comment by Greelan** [comment]
Yeah, good job for trying. Though from a quick look it needs quite a bit of clean up. If you get stuck ping me and I will bash it info shape pretty quickly

**Comment by BlueBackbite** [comment]
@Greelan Yeah, if you could take a whack at this, I've been trying to reference approved KVP configs and am missing some information here.

**Comment by Greelan** [comment]
No worries, it's done, just away from my laptop for the weekend, will push it to my repo when back

**Comment by Greelan** [comment]
The template is in `Greelan/AMPTemplates:dev`

Couple of things:
- A socket is not opened on the game port. I reckon the server is using Steam sockets and so the game port is irrelevant
- The SandboxSettings.ini file is not created. Dunno why

**Comment by BlueBackbite** [comment]
Attempted to run your configuration @Greelan on a windows host and the server config page doesn't populate in amp for some reason. (Haven't setup my linux server host for docker yet.)
Also the INI is only pulled from their github as an example, why ini generation isn't a part of the code is beyond me. (https://github.com/DFJacob/AbioticFactorDedicatedServer/blob/main/SandboxSettings.ini)

I copied your configuration and fiddled with it, got the server configuration page to show, but broke starting the server. I'm going to try and get it to come up after starting over.

**Comment by Greelan** [comment]
If you have a controller/target setup then you need to make sure the repo is added to both and is up to date on both. Otherwise that can lead to the config manifest not populating. 

I can have the template supply the ini, just wasn't sure whether a central ini for all saves was the way to go (some hosters seem to do that) or instead separate per save. Anyway, the server doesn't seem to create individual saves.

**Comment by BlueBackbite** [comment]
Nope, I'm just an idiot. I didn't notice you renamed it to "AF Server Settings" Everything seems to be working fine.

**Comment by Greelan** [comment]
Cool. I didn't technically rename anything, I prepared the template from scratch xD

Thoughts about the ini? Just pop it in Saved/Config to apply globally?

**Comment by BlueBackbite** [comment]
It seems like dropping it in Saved/Config would work, I can't think of anything better personally.
Then again I'm still attempting to learn more about the AMP ecosystem.

**Comment by Greelan** [comment]
That's not an AMP question, it's a server question. I will go that path
