### ISSUE TITLE
Any simple file sharing app that uses link sharing?

### ISSUE THREAD

**Issue by Warscarz** [CubeCoders/AMPTemplates#773]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title:
How to obtain: https://
Suppoted OSs:
Supports RCON/Console input?

## I confirm:

- [ x] that I have searched for an existing module request for this application.
- [ ] that the server is an official server distributed by the games publishers/developers.
- [ ] that the server is available to the general public.
- [ ] that the server can be run headless (without a GUI).
- [ x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Warscarz** [comment]
Thanks for the support...

**Comment by BroOtti** [comment]
> Thanks for the support...

This is not support. If you need support join discord or head to the forums.
If you still want to request a new module, create a new request and fill in the template properly.

**Comment by Warscarz** [comment]
![image](https://github.com/CubeCoders/AMPTemplates/assets/169658781/7c702993-2719-4863-a5d2-1b09f1bd4252)

**Comment by Warscarz** [comment]
ProjectSend could be ran in an instance, as far as I understand. Sadly I am too much of a noob to linux...
