### ISSUE TITLE
Request Soulmask

### ISSUE THREAD

**Issue by Tekmoller** [CubeCoders/AMPTemplates#811]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:
I'm requesting that Soulmask be added to the list of supported games.

Game Title:
Soulmask

Link to game:
https://store.steampowered.com/app/2646460/Soulmask/

Link for the download:
https://steamdb.info/app/2889410/ (Linux)
https://steamdb.info/app/2886870/ (Windows)

Suppoted OSs:
Windows, Linux

Supports RCON/Console input?
I believe so but I could not get this working manually or find more info.

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
An initial draft template is in my dev branch. Can't be tested and finalised until the server files are released.

**Comment by Tekmoller** [comment]
I would be happy if you could let me know if you were able to test it :-)

**Comment by Greelan** [comment]
Yes, it is working

**Comment by darkt1981** [comment]
> An initial draft template is in my dev branch. Can't be tested and finalised until the server files are released.

where is it could you please link it.

**Comment by Greelan** [comment]
`Greelan/AMPTemplates:dev`

Add that to your config repos in AMP.

**Comment by DarthPooh79** [comment]
> `Greelan/AMPTemplates:dev`
> 
> Add that to your config repos in AMP.

I added this repo and after clicking on fetch, it does not update to show Soulmask as a creatable instance

**Comment by Quantwan** [comment]
> > `Greelan/AMPTemplates:dev`
> 
> > 
> 
> > Add that to your config repos in AMP.
> 
> 
> 
> I added this repo and after clicking on fetch, it does not update to show Soulmask as a creatable instance

Just add it, hit Fetch and create new instance. Its called Greenlan / Soulmask.

**Comment by DarthPooh79** [comment]
> > > `Greelan/AMPTemplates:dev`
> > 
> > 
> > > 
> > 
> > 
> > > Add that to your config repos in AMP.
> > 
> > 
> > I added this repo and after clicking on fetch, it does not update to show Soulmask as a creatable instance
> 
> Just add it, hit Fetch and create new instance. Its called Greenlan / Soulmask.

this doesn't work for me, and it doesnt show up either under Greenlan or Soulmask.  Been at it for a minute, I can install it through SteamCMD and get it running just fine, but I'd rather it go through AMP

**Comment by Greelan** [comment]
If you are on windows, make sure git is installed and is in the system path

**Comment by Greelan** [comment]
And it's Greelan, Greenlan

**Comment by DarthPooh79** [comment]
> And it's Greelan, not Greenlan

Sorry, I did use Greelan and I am not following, sorry, install github?  The desktop app?  I didn't think I needed that to scrap the repo from within AMP.

**Comment by YourHuckleberry** [comment]
Confirmed working.  Found this on Steam, should help to flesh out the config options:

`"ExpRatio": 1,
"CaiJiDiaoLuoRatio": 1, // Gathering Drop Ratio
"FaMuDiaoLuoRatio": 1, // Logging Drop Ratio
"CaiKuangDiaoLuoRatio": 1, // Mining Drop Ratio
"DongWuShiTiDiaoLuoRatio": 1, // Animal Corpses Drop Ratio
"DongWuShiTiZhongYaoDiaoLuoRatio": 1, // Important Animal Corpses Drop Ratio
"CaiJiShengChanJianZhuDiaoLuoRatio": 1, // Gathering Production Building Drop Ratio
"PuTongRenDiaoLuoRatio": 1, // Ordinary People Drop Ratio
"JingYingRenDiaoLuoRatio": 1, // Elite People Drop Ratio
"BossRenDiaoLuoRatio": 1, // Boss People Drop Ratio
"ZuoWuDropRatio": 1, // Crops Drop Ratio
"AddRenKeDuRatio": 1, // Human Resistance Ratio
"ZuoWuShengZhangRatio": 1, // Crop Growth Ratio
"BinSiKaiGuan": 1, // Death Switch
"JianZhuFuLanMul": 1, // Building Decay Multiplier
"JianZhuXiuLiMul": 1, // Building Repair Multiplier
"JianZhuFuLanKaiGuan": 1, // Building Decay Switch
"ZhiZuoTimeRatio": 1, // Manufacturing Time Ratio
"DamageYeShengRatio": 1, // Damage from Wild Ratio
"BeDamageByYeShengRatio": 1, // Damage by Wild Ratio
"GameWorldDayTimePortion": 0.69999998807907104,
"GameWorldTimePower": 24,
"BaoXiangDropRatio": 1, // Treasure Chest Drop Ratio
"HuXIangShangHaiKaiGuan": 0, // Mutual Damage Switch
"ZhiBeiChongShengRatio": 1, // Prepared Rebirth Ratio
"ChengZhangExpRatio": 1, // Growth Experience Ratio
"MJExpRatio": 1,
"ShuLianDuExpRatio": 1, // Skill Level Experience Ratio
"NaiJiuXiShu": 1, // Durability Coefficient
"ReDuXiShu": 1, // Heat Coefficient
"CaiJiExpRatio": 1, // Gathering Experience Ratio
"ZhiZuoExpRatio": 1, // Manufacturing Experience Ratio
"ShaGuaiExpRatio": 1, // Slay Monsters Experience Ratio
"QiTaExpRatio": 1, // Other Experience Ratio
"BeiDongYiJiShuXingRatio": 1, // Passive Skill Attributes Ratio
"ZhuDongYiJiShuXingRatio": 1, // Active Skill Attributes Ratio
"ErJiShuXingRatio": 1, // Secondary Attributes Ratio
"MaRenBeiDongYiJiShuXingRatio": 1, // Horseman Passive Skill Attributes Ratio
"MaRenZhuDongYiJiShuXingRatio": 1,
"MaRenErJiShuXingRatio": 1,
"DongWuBeiDongYiJiShuXingRatio": 1, // Animal Passive Skill Attributes Ratio
"DongWuZhuDongYiJiShuXingRatio": 1,
"DongWuErJiShuXingRatio": 1,
"ShiWuXiaoHaoRatio": 1, // Food Consumption Ratio
"ShuiXiaoHaoRatio": 1, // Water Consumption Ratio
"QiXiXiaoHaoRatio": 1, // Breath Consumption Ratio
"ShengMingHuiFuRatio": 1, // Health Recovery Ratio
"TiLiHuiFuRatio": 1, // Stamina Recovery Ratio
"QiXiHuiFuRatio": 1, // Breath Recovery Ratio
"DongWuDamageRatio": 1, // Animal Damage Ratio
"DongWuJianShangRatio": 1, // Animal Damage Reduction Ratio
"MaRenDamageRatio": 1, // Horseman Damage Ratio
"ManRenJianShangRatio": 1, // Horseman Damage Reduction Ratio
"JiaSiHuiFuRatio": 1, // Family Recovery Ratio
"CaiJiDamageRatio": 1, // Gathering Damage Ratio
"ZiYuanShengMingRatio": 1, // Resource Life Ratio
"RanLiaoXiaoHaoRatio": 1, // Fuel Consumption Ratio
"DongWuShengZhangRatio": 1, // Animal Growth Ratio
"FanZhiJianGeRatio": 1, // Breeding Interval Ratio
"DongWuShengChanJianGeRatio": 1, // Animal Production Interval Ratio
"DongWuChanChuRatio": 1, // Animal Output Ratio
"DongWuXiaoHaoShiWuRatio": 1, // Animal Food Consumption Ratio
"DongWuXiaoHaoShuiRatio": 1, // Animal Water Consumption Ratio
"ZuoWuFeiLiaoXiaoHaoRatio": 1, // Crop Fertilizer Consumption Ratio
"ZuoWuShuiXiaoHaoRatio": 1, // Crop Water Consumption Ratio
"ZuoWuXiaoHuiRatio": 1, // Crop Decay Ratio
"GongJiJianZhuDamageRatio": 1, // Attack Building Damage Ratio
"DongWuPinZhiRatio": 1, // Animal Quality Ratio
"ManRenPinZhiRatio": 1, // Horseman Quality Ratio
"WanJiaZiYuanJinShuaBanJing": 1, // Player Resource Refresh Radius
"JianZhuZiYuanJinShuaBanJing": 1, // Building Resource Refresh Radius
"WuPinFuHuaiRatio": 1, // Item Decay Ratio
"WuPinXiaoHuiTime": 1, // Item Destruction Time
"XiuLiXuYaoCaiLiaoRatio": 1, // Repair Material Needed Ratio
"XiuLiJiangNaiJiuShangXianRatio": 1, // Repair Durability Limit Reduction Ratio
"RuQinKaiGuan": 1, // Invasion Switch
"RuQinGuiMoXiShu": 1, // Invasion Scale Coefficient
"RuQinQiangDuXiShu": 1, // Invasion Strength Coefficient
"RuQinGuaiCountMin": 8, // Minimum Invasion Monster Count
"RuQinGuaiCountMax": 128, // Maximum Invasion Monster Count
"RuQinPerBoGuaiMin": 3, // Minimum Monsters Per Wave in Invasion
"RuQinPerBoGuaiMax": 16, // Maximum Monsters Per Wave in Invasion
"RuQinGuaiLevelXiShu": 1, // Invasion Monster Level Coefficient
"TanChaMinuteLimit": 20, // Exploration Minute Limit
"JinGongMinuteLimit": 90, // Attack Minute Limit
"LengQueMinuteLimit": 1440, // Cooldown Minute Limit
"ChongsuRatio": 1, // Recharge Ratio
"RuQinMaxChangCiCount": 2, // Maximum Invasion Occurrences Count
"RuQinBeginHour": 0, // Invasion Start Hour
"RuQinEndHour": 24, // Invasion End Hour
"RuQinShaoChengXiShu": 0.60000002384185791, // Invasion Burn Coefficient
"RuQinTuShaXiShu": 0.30000001192092896, // Invasion Massacre Coefficient
"XiuMianDistance": 10000, // Rest Distance
"HuanXingDistance": 9000, // Awakening Distance
"GongHuiMaxZhaoMuCount": 50, // Guild Maximum Recruitment Count
"GeRenMaxZhaoMuCount": 6, // Individual Maximum Recruitment Count
"GeRenMaxZhaoMuCount_Two": 10, // Individual Maximum Recruitment Count for Two
"GeRenMaxZhaoMuCount_Three": 15, // Individual Maximum Recruitment Count for Three
"XinQingZengZhang": 1, // Mood Increase
"XinQingJianShao": 1, // Mood Decrease
"XiShuWeiLing": 0, // Coefficient Unassigned
"HuiFuChuShiBodyData": 1, // Recover Initial Body Data
"YouFangShangHaiKaiGuan": 0, // Friendly Fire Switch
"YeShengHitJianZhuShangHaiRatio": 4, // Wild Animal Hits Building Damage Ratio
"PVP_ShangHaiRatio_WithoutP2P_YouFang": 0, // PVP Damage Ratio without Player to Player on Friendly Side
"WanJiaHitJianZhuShangHaiRatio": 1, // Player Hits Building Damage Ratio
"ShaGuaiExpShareRatio": 0.20000000298023224, // Share Monster Slaying Experience Ratio
"YunXuOtherDaKaiGongZuoTai": 0, // Allow Others to Open Workbench
"YunXuOtherDaKaiXiangZi": 0, // Allow Others to Open Box
"PVP_ShangHaiRatio_JinZhan": 0.40000000596046448, // PVP Melee Damage Ratio
"PVP_ShangHaiRatio_YuanCheng": 0.40000000596046448, // PVP Ranged Damage Ratio
"GongHuiMaxDongWuCount": 50, // Guild Maximum Animal Count
"GeRenMaxDongWuCount": 10, // Individual Maximum Animal Count
"SuiJiRuQinKaiGuan": 1, // Random Invasion Switch
"PanpaKaiGuan": 1, // Panic Switch
"WanJiaBeiXiaoRenRatio": 0.80000001192092896, // Player Being Laughed At Ratio
"WanJiaBeiXiaoTiRatio": 0.80000001192092896, // Player Being Ridiculed Ratio
"KaiQiJianZhuHuiXueBuilding": 1, // Enable Building Regeneration
"PVP_ShangHaiRatio_PlayerToPlayer_DiFang": 1, // PVP Damage Ratio Player to Player Enemy
"PVP_GAPVPDamageRatio": 1,
"PlayerYouFangShangHaiKaiGuan": 1, // Player Friendly Fire Switch
"MeiTiShiWanKaiGuan": 0, // Media Trial Switch
"PVP_ShangHaiRatio_PlayerToPlayer_YouFang": 0.059999998658895493, // PVP Damage Ratio Player to Player Friendly Side
"BaoXiangDiaoLuoDengJi": 0, // Treasure Chest Drop Level
"KaiQiKuaFu": 0, // Enable Cross-Server
"FuHuaSpeed": 1, // Decay Speed
"YingHuoRanShaoSuDuRatio": 1, // Fire Burning Speed Ratio
"HuDongExcludeBetweenCameraCharacter": 1, // Interaction Exclusion Between Camera and Character
"PVPTimeAsiaWorkStartTime": 0,
"PVPTimeAsiaWorkEndTime": 24,
"PVPTimeAsiaNoWorkStartTime": 0,
"PVPTimeAsiaNoWorkEndTime": 24,
"PVPTimeAmericaWorkStartTime": 0,
"PVPTimeAmericaWorkEndTime": 24,
"PVPTimeAmericaNoWorkStartTime": 0,
"PVPTimeAmericaNoWorkEndTime": 24,
"PVPTimeEuropeWorkStartTime": 0,
"PVPTimeEuropeWorkEndTime": 24,
"PVPTimeEuropeNoWorkStartTime": 0,
"PVPTimeEuropeNoWorkEndTime": 24,
"WuLiYouHuaDist": 6666, // Physics Optimization Distance
"MovementYouHua": 1, // Movement Optimization
"XiuMianOfflineDays": 7, // Rest Offline Days
"WanJiaShiWanKaiGuan": 0, // Player Trial Switch
"WuLiYouHuaKaiGuan": 1, // Physics Optimization Switch
"TiaoWuLengQueTime": 4, // Dancing Cooldown Time
"MaxLevel": 60,
"PVEOnlyTongGuiShuCanOpenKaiGuan": 1, // PVE Only Same Faction Tree Can Open Switch
"TeShuDaoJuDropXiShuJiaChengKaiGuan": 0, // Special Tool Drop Coefficient Boost Switch
"JianZhuChuanSongMenPlusKaiGuan": 0, // Building Transport Door Plus Switch
"FuHuoMoveSiWangBaoKaiGuan": 0 // Revive Move Death Explosion Switch`

**Comment by Jerrakon** [comment]
I also have the problem that nothing is displayed to me when creating a new instance. I also installed everything I needed.

**Comment by SneakyTax** [comment]
> How do you add this to the Linux server - or does it only work on Windows? (V-Rising/Icarus/etc dedicated servers are Windows-only but configures using Docker + Wine)

Disregard - found it under --> Configuration Repositories
