### ISSUE TITLE
American Truck Simulator now supports 128 players - Can you please update the template? 

### ISSUE THREAD

**Issue by CanadAcoustics** [CubeCoders/AMPTemplates#817]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: American Truck Simulator
How to obtain: https://
Suppoted OSs: Windows/Linux
Supports RCON/Console input?

## I confirm:

- [x ] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x ] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

Hi, 

As of two weeks ago, American Truck Simulator supports up to 128 players. Within the game you can 'host your own session up to 128 players', or dedicated servers are now supporting up to 128 players. 

Can you please update the template? 

Regards

**Comment by ssfdre38** [comment]
Updated ats and ets2. Can be closed now
