### ISSUE TITLE
Beasts of Bermuda

### ISSUE THREAD

**Issue by alanman87** [CubeCoders/AMPTemplates#831]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/
I don't understand this at all.

## Game Information:

Game Title: Beasts of Bermuda
How to obtain: https://store.steampowered.com/app/719890/
Suppoted OSs: Windows
Supports RCON/Console input? Yes? Idk

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool

**Comment by Greelan** [comment]
A template has existed for around 12 months in my dev branch

**Comment by alanman87** [comment]
My mistake. It would be nice if more of these were moved to the official supported list so they're easy to find. I am not able to test for a few days so we can close this request.

**Comment by Greelan** [comment]
This particular was put there because I was helping someone else to get it running. Can't recall why I left it there - I think it was a bit undercooked in terms of settings configuration and might have had console issues
