### ISSUE TITLE
Arma Reforger config disableNavmeshStreaming syntax change with 1.2 update

### ISSUE THREAD

**Issue by jhendrix99** [CubeCoders/AMPTemplates#852]
With the drop of version 1.2, the current config prevents servers from starting. The new syntax is to us an array instead of boolean. The setting is not 100% needed for server operation, possibly removing as a hotfix until their documentation is updated would suffice unless someone has a source for the new syntax.

**Comment by Greelan** [comment]
A temporary fix of removing the setting from server.json has been implemented - update your server to get the change. The setting will be re-added once it is clear on the best way to implement it for 1.2
