### ISSUE TITLE
The isle Evrima requires updating 

### ISSUE THREAD

**Issue by regchanuk** [CubeCoders/AMPTemplates#929]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: the isle Everima
How to obtain: https://
Suppoted OSs:
Supports RCON/Console input?

updated server comands for server   
main one bEnableMutations=true // Enable mutations.

### **Below is an updated Game.ini for Server Owners:**

[/Script/TheIsle.TIGameStateBase]
AdminsSteamIDs=Admin steam ID here // SteamID64 format
WhitelistIDs=White list steam ID here // SteamID64 format. NOTE: Must be enabled in the game session below. Keep this empty if whitelist is disabled
// List of all enabled classes. Remove a line to remove a class from spawning. - Can also be managed in Admin Panel in real time.
AllowedClasses=Hypsilophodon
AllowedClasses=Pachycephalosaurus
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Omniraptor
AllowedClasses=Pteranodon
AllowedClasses=Troodon
AllowedClasses=Beipiaosaurus
AllowedClasses=Gallimimus
AllowedClasses=Dilophosaurus
AllowedClasses=Herrerasaurus

HERE

// List of all enabled mutations and values. Keep commented out to have all mutations enabled. Enabling any mutations means you must include all mutations you would like available on your server. Listed below are all modifiable mutations with default values. Altering these values may produce unstable gameplay.
// EnabledMutations=Hemomania, 0.05
// EnabledMutations=Hematophagy, 0.25
// EnabledMutations=Accelerated Prey Drive, 0.1
// EnabledMutations=Xerocole Adaptation, 0.2
// EnabledMutations=Hypervigilance, 0.5
// EnabledMutations=Truculency, 0.2
// EnabledMutations=Osteophagic, 0.15
// EnabledMutations=Photosynthetic Regeneration, 0.1
// EnabledMutations=Cellular Regeneration, 0.15
// EnabledMutations=Advanced Gestation, 0.5
// EnabledMutations=Sustained Hydration, 0.2
// EnabledMutations=Enlarged meniscus, 0.15
// EnabledMutations=Efficient Digestion, 0.2
// EnabledMutations=Featherweight, 0.5
// EnabledMutations=Osteosclerosis, 0.2
// EnabledMutations=Wader, 0.25
// EnabledMutations=Epidermal Fibrosis, 0.15
// EnabledMutations=Congenital Hypoalgesia, 0.15
// EnabledMutations=Photosynthetic Tissue, 0.05
// EnabledMutations=Nocturnal, 0.05
// EnabledMutations=Hydroregenerative, 0.25
// EnabledMutations=Increased Inspiratory Capacity, 0.15
// EnabledMutations=Hydrodynamic, 0.15
// EnabledMutations=Submerged Optical Retention, 0.05
// EnabledMutations=Infrasound Communication, 0.5
// EnabledMutations=Augmented Tapetum, 0.5
// EnabledMutations=Hypermetabolic Inanition, 0.15
// EnabledMutations=Tactile Endurance, 0.5
// EnabledMutations=Gastronomic Regeneration, 0.1
// EnabledMutations=Heightened Ghrelin, 0.25
// EnabledMutations=Prolific Reproduction, 0.1
// EnabledMutations=Enhanced Digestion, 0.1
// EnabledMutations=Reinforced Tendons, 0.1
// EnabledMutations=Multichambered Lungs, 0.05
// EnabledMutations=Reabsorption, 1 ****** // Value must be 1 or remove from this list to disable it.
// EnabledMutations=Pit Organ, 1 ******// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Cannibalistic, 1 ******// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Barometric Sensitivity, 1 ******// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Social Behavior, 1 *****// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Traumatic Thrombosis, 1 *****// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Reniculate Kidneys, 1 *****// Value must be 1 or remove from this list to disable it.
// EnabledMutations=Paratrepsis, 1 ****// Value must be 1 or remove from this list to disable it.

[/Script/TheIsle.TIGameSession]
ServerName="Server name here" // Server name.
MaxPlayerCount=100 // 100+ player servers is not recommended.
bEnableHumans=false // Set to true if you want to run around with a flashlight and kick an animal.
bQueueEnabled=true // Enable queue if server slots are all filled.
QueuePort=1000 // Queue port.
bServerPassword=false // Set to true if you want a server password.
ServerPassword="password here" // Your server password.
bRconEnabled=true // Enable RCON.
RconPassword="password here" // RCON password. Do not give this out.
bServerDynamicWeather=true // Temporarily disabled. Changing this will do nothing.
ServerDayLengthMinutes=45 // Set in minutes.
ServerNightLengthMinutes=20 // Set in minutes.
bServerWhitelist=false // Set the server whitelist. If true, will look for whitelistID's in the above category.
bEnableGlobalChat=false // Enabling the Global Chat panel.
bSpawnPlants=true // Enable plant food spawns.
bSpawnAI=true // Enable AI spawns.
AISpawnInterval=40 // Set how frequently AI can spawn in seconds.
bEnableMigration=true // Enable patrol zones, species migrations, and mass migrations.
MaxMigrationTime=5400 // Value is in seconds. This controls how long the migration zones should last.
GrowthMultiplier=1 - Universal multiplier for growth. Putting this number too high will break it. Recommendation is no higher than 20, even for lulz.
bEnableMutations=true // Enable mutations.

// Add the names of each AI class that should be disabled, one line for each.
// DisallowedAIClasses=Compsognathus
// DisallowedAIClasses=Pterodactylus
// DisallowedAIClasses=Boar
// DisallowedAIClasses=Deer
// DisallowedAIClasses=Goat
// DisallowedAIClasses=Seaturtle

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [x] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [x] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by regchanuk** [comment]
also a slight bug the game is not fully starting in web console

**Comment by Greelan** [comment]
#927
