### ISSUE TITLE
Pixark server setup errors

### ISSUE THREAD

**Issue by OldYeti-gif** [CubeCoders/AMPTemplates#931]
When trying to start up the server it seems to download everything fine but when looking into the console it spits out a lot of errors that just repeat and stop the server from working not sure what the problem is entirely. 
![Screenshot 2024-08-07 225510](https://github.com/user-attachments/assets/31e134d1-1fb7-43e4-81e4-120441e301d6)
![Screenshot 2024-08-07 225549](https://github.com/user-attachments/assets/a8ad4f77-ef75-49b7-bc60-6f65202bd509)

**Comment by Greelan** [comment]
Don't see any errors there, only warnings. What makes you say the server is not working properly? Have you installed the dependencies for the server?

**Comment by OldYeti-gif** [comment]
What dependencies do I need?

**Comment by OldYeti-gif** [comment]
It got past CubeWorldServer:Warning: compose_generator.cpp 66 cubesvr::CComposeGenerator::ComposeColumn biome not exists. 255. Now its giving me this repeatedly. 
![Screenshot 2024-08-07 233456](https://github.com/user-attachments/assets/c43557f2-f2b9-4d1c-819c-ef108eea7f0d)

**Comment by Greelan** [comment]
Yep, but so what? Are all the ports listening?

**Comment by OldYeti-gif** [comment]
Yes it says all ports are listening.

**Comment by Greelan** [comment]
I don't understand the issue then

**Comment by OldYeti-gif** [comment]
The server isn't actually starting it gets stuck in a endless loop.

**Comment by OldYeti-gif** [comment]
I see the server in my server browser on the game but if I try to join I get a connection timeout. If I stop the server it tells me that PixARKServer.exe is a unknown function and that 0 bytes have been written.
![Screenshot 2024-08-07 233456](https://github.com/user-attachments/assets/2abeba5a-79b8-48e4-b598-418c0d957c7e)

**Comment by KainRacure** [comment]
> When trying to start up the server it seems to download everything fine but when looking into the console it spits out a lot of errors that just repeat and stop the server from working not sure what the problem is entirely. ![Screenshot 2024-08-07 225510](https://private-user-images.githubusercontent.com/177559209/356064385-31e134d1-1fb7-43e4-81e4-120441e301d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc3MzAsIm5iZiI6MTcyMzk1NzQzMCwicGF0aCI6Ii8xNzc1NTkyMDkvMzU2MDY0Mzg1LTMxZTEzNGQxLTFmYjctNDNlNC04MWU0LTEyMDQ0MWUzMDFkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzBjNTJhOTI4N2Y1ODYxMjlmOWI5M2MwNjk5MDA3ZTZhMjA1NThiNDA1YWE0ODU3NWYzNWQ3MjI3Zjk5MDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UKJ9IrZlYVvYKX0EjgOoY6AaM4hFWRT6V7Ct98TniDU) ![Screenshot 2024-08-07 225549](https://private-user-images.githubusercontent.com/177559209/356064395-a8ad4f77-ef75-49b7-bc60-6f65202bd509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc3MzAsIm5iZiI6MTcyMzk1NzQzMCwicGF0aCI6Ii8xNzc1NTkyMDkvMzU2MDY0Mzk1LWE4YWQ0Zjc3LWVmNzUtNDliNy1iYzYwLTZmNjUyMDJiZDUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzE1MzgzODdjZTk5NGJmMGYxZjViOGY5YWEzMWEwOWY3ZTFiOTExNzZhOThmZmY3NzY2ZjdmZjk2MjQxOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3X_MCmKIem-guzULH3WEtB2XqE6DV50u6Ci-pnkLDjM)

I am having the EXACT same issue as the OP.
