### ISSUE TITLE
New Setting for Palworld Servers

### ISSUE THREAD

**Issue by Nyhmus** [CubeCoders/AMPTemplates#980]
# Request
Please add the new DLC-Setting "SupplyDropSpan" to the Palworld Server Settings.

## Setting Information:
The Setting is for the Supplydrop- and Meteordropchance. It describes how often it can happen in minutes.
SupplyDropSpan=10 -> every10 minutes

Default setting seems to be 180 minutes

**Comment by Greelan** [comment]
It was added several weeks ago

**Comment by Nyhmus** [comment]
Sorry, Template wasn't updated on the instance. Thought it used the updated one because i created the instance as new one.

**Comment by Greelan** [comment]
Not unreasonable to expect that to be the case...
