### ISSUE TITLE
Satisfactory v1.0 changes

### ISSUE THREAD

**Issue by AWL-Gaming** [CubeCoders/AMPTemplates#994]
AMP is in a continuous update loop after the recent major Satisfactory v1.0 release.
![image](https://github.com/user-attachments/assets/edb88211-95fe-4d3c-8692-b8aa44b6c40a)
Server cannot be started at all, just keeps updating over and over again (despite AMP's instance settings being set to start only and not update)

**Comment by RaymondShell** [comment]
for the server to start it only requires the actual server application be updated. but beyond that it still doesn't work

**Comment by AWL-Gaming** [comment]
> for the server to start it only requires the actual server application name be updated. but beyond that it still doesn't work
Correct; the server starts normally through the exe but still haven't tried the AMP side with the updated name.

```properties
[15:22:53] [steamcmdplugin:Med Info/21] : SteamCMD Update successful
[15:22:53] [Generic: Info/21]  : Specified executable 'D:\AMPDatastore\Instances\AWL01\satisfactory\1690800\Engine\Binaries\Win64\UnrealServer-Win64-Shipping.exe does not exist. Updating application...
```

**Comment by Tobiti** [comment]
So after changing the start application the server is running, but I cant connect to it :/

**Comment by AWL-Gaming** [comment]
Fixed by changing the executable line (at least for Windows):
From `App.ExecutableWin=1690800\Engine\Binaries\Win64\UnrealServer-Win64-Shipping.exe`
To
`App.ExecutableWin=1690800\Engine\Binaries\Win64\FactoryServer-Win64-Shipping.exe`
![image](https://github.com/user-attachments/assets/5f2e420e-ffc2-462e-8b0f-a3fcdf3866e3)

Need the above changes updated in https://github.com/CubeCoders/AMPTemplates/blob/main/satisfactory.kvp

**Comment by Tobiti** [comment]
So im running it on linux and after changing the executable path to the right one, the server is starting, but I get this error ingame
![image](https://github.com/user-attachments/assets/9db89e71-5894-49af-8aec-02c815541115)

It was working before the update

**Comment by darkace1998** [comment]
the server changed from 3 ports to 1 port 7777udp and tcp need to be open

**Comment by darkace1998** [comment]
you need to remove the multihome option from the start that breaks the joining process the http server is only for 3r party intigrations no need for joining the server

**Comment by IceOfWraith** [comment]
This has been updated.

For new instances - Search in the top right of AMP for Repo and click the Fetch button and make a new instance.

For existing instances - Update the instance from the main ADS screen and choose to update the Template if prompted. Also update inside the instance to get the latest game version.
